export const AWESOME_SKILL_SCHEMA = 'awesome-skill.v1'

export const AWESOME_SKILL_CATEGORIES = [
  { id: 'design', label: 'DESIGN' },
  { id: 'creation', label: 'CREATION' },
  { id: 'engineering', label: 'ENGINEERING' },
  { id: 'agents', label: 'AGENTS' },
  { id: 'research', label: 'RESEARCH' },
  { id: 'hardware', label: 'HARDWARE' },
] as const

export type AwesomeSkillCategory = (typeof AWESOME_SKILL_CATEGORIES)[number]['id']

export const AWESOME_SKILL_KINDS = [
  { id: 'instructions', label: 'INSTRUCTIONS' },
  { id: 'scripts', label: 'SCRIPTS' },
  { id: 'mcp', label: 'MCP' },
  { id: 'assets', label: 'ASSETS' },
  { id: 'templates', label: 'TEMPLATES' },
] as const

export type AwesomeSkillKind = (typeof AWESOME_SKILL_KINDS)[number]['id']

export const AWESOME_SKILL_COMPATIBILITY = [
  { id: 'codex', label: 'CODEX' },
  { id: 'claude', label: 'CLAUDE' },
  { id: 'dsh', label: 'DSH' },
  { id: 'generic', label: 'GENERIC' },
] as const

export type AwesomeSkillCompatibility = (typeof AWESOME_SKILL_COMPATIBILITY)[number]['id']

export const AWESOME_SKILL_MATURITY = [
  { id: 'collected', label: 'COLLECTED' },
  { id: 'audited', label: 'AUDITED' },
  { id: 'tried', label: 'TRIED' },
  { id: 'proven', label: 'PROVEN' },
] as const

export type AwesomeSkillMaturity = (typeof AWESOME_SKILL_MATURITY)[number]['id']

export const AWESOME_SKILL_PERMISSIONS = [
  { id: 'read-only', label: 'READ-ONLY' },
  { id: 'filesystem', label: 'FILESYSTEM' },
  { id: 'network', label: 'NETWORK' },
  { id: 'shell', label: 'SHELL' },
  { id: 'credentials', label: 'CREDENTIALS' },
] as const

export type AwesomeSkillPermission = (typeof AWESOME_SKILL_PERMISSIONS)[number]['id']

export const AWESOME_SKILL_EFFORTS = [
  { id: '5-min', label: '5 MIN' },
  { id: '30-min', label: '30 MIN' },
  { id: 'half-day', label: 'HALF DAY' },
] as const

export type AwesomeSkillEffort = (typeof AWESOME_SKILL_EFFORTS)[number]['id']

export type AwesomeSkillLicenseStatus = 'clear' | 'review' | 'restricted'

export interface AwesomeSkillDossier {
  schema: typeof AWESOME_SKILL_SCHEMA
  upstreamName: string
  category: AwesomeSkillCategory
  kinds: AwesomeSkillKind[]
  compatibility: AwesomeSkillCompatibility[]
  permissions: AwesomeSkillPermission[]
  maturity: AwesomeSkillMaturity
  effort: AwesomeSkillEffort
  license: string
  licenseStatus: AwesomeSkillLicenseStatus
  artifact: string
  whyItMatters: string
  firstLook: string
  auditNote: string
  skillUrl: string
  promptSlug?: string
}

export interface AwesomeSkillSeed {
  title: string
  slug: string
  summary: string
  websiteUrl: string
  sourceUrl: string
  sortOrder: number
  dossier: AwesomeSkillDossier
}

export const AWESOME_SKILL_FEEDS = [
  {
    name: 'AGENT SKILLS',
    scope: 'OPEN SPECIFICATION',
    url: 'https://agentskills.io/',
  },
  {
    name: 'OPENAI SKILLS',
    scope: 'CODEX CATALOG',
    url: 'https://github.com/openai/skills',
  },
  {
    name: 'ANTHROPIC SKILLS',
    scope: 'REFERENCE SKILLS',
    url: 'https://github.com/anthropics/skills',
  },
  {
    name: 'VERCEL AGENT SKILLS',
    scope: 'WEB ENGINEERING',
    url: 'https://github.com/vercel-labs/agent-skills',
  },
  {
    name: 'AWESOME COPILOT',
    scope: 'COMMUNITY CATALOG',
    url: 'https://github.com/github/awesome-copilot',
  },
  {
    name: 'MICROSOFT SKILLS',
    scope: 'AZURE + FOUNDRY',
    url: 'https://github.com/microsoft/skills',
  },
  {
    name: 'DEEPSEEK HARNESS',
    scope: 'DSH SKILL SYSTEM',
    url: 'https://github.com/deepseek-ai/deepseek-harness/tree/master/.agents/skills',
  },
  {
    name: 'PRESENTATION SKILLS',
    scope: 'DECK PRODUCTION',
    url: 'https://github.com/appautomaton/presentation',
  },
  {
    name: 'K-12 TEACHER SKILLS',
    scope: 'LESSON DESIGN',
    url: 'https://github.com/anthropics/k12-teacher-skills',
  },
] as const

export const AWESOME_SKILLS: AwesomeSkillSeed[] = [
  {
    title: 'Frontend Design',
    slug: 'awesome-skill-anthropic-frontend-design',
    summary: '从主题、排版、结构和动效入手，避免把前端做成可替换的模板答案。',
    websiteUrl: 'https://github.com/anthropics/skills/tree/main/skills/frontend-design',
    sourceUrl: 'https://github.com/anthropics/skills',
    sortOrder: 10,
    dossier: {
      schema: AWESOME_SKILL_SCHEMA,
      upstreamName: 'anthropics/skills · frontend-design',
      category: 'design',
      kinds: ['instructions'],
      compatibility: ['claude', 'generic'],
      permissions: ['read-only', 'filesystem'],
      maturity: 'collected',
      effort: '30-min',
      license: 'CUSTOM TERMS · REVIEW LICENSE.txt',
      licenseStatus: 'review',
      artifact: 'DISTINCT UI DIRECTION',
      whyItMatters: '它把视觉选择拉回具体主题与真实内容，适合在页面开发前建立清晰而非模板化的方向。',
      firstLook: '先读触发条件、设计流程和版权边界，再用一个独立页面做小范围对照，不直接套进全站。',
      auditNote: '仓库公开，但 Skill frontmatter 指向单独 LICENSE.txt；商用或再分发前必须复核完整条款。',
      skillUrl: 'https://github.com/anthropics/skills/blob/main/skills/frontend-design/SKILL.md',
    },
  },
  {
    title: 'Algorithmic Art',
    slug: 'awesome-skill-anthropic-algorithmic-art',
    summary: '用 p5.js、种子随机与参数探索制作可复现的生成艺术。',
    websiteUrl: 'https://github.com/anthropics/skills/tree/main/skills/algorithmic-art',
    sourceUrl: 'https://github.com/anthropics/skills',
    sortOrder: 20,
    dossier: {
      schema: AWESOME_SKILL_SCHEMA,
      upstreamName: 'anthropics/skills · algorithmic-art',
      category: 'creation',
      kinds: ['instructions', 'scripts', 'templates'],
      compatibility: ['claude', 'generic'],
      permissions: ['filesystem', 'network'],
      maturity: 'collected',
      effort: 'half-day',
      license: 'CUSTOM TERMS · REVIEW LICENSE.txt',
      licenseStatus: 'review',
      artifact: 'SEEDED P5.JS STUDY',
      whyItMatters: '它不是生成一张孤立图片，而是把审美变成可重复、可调参、可比较的代码作品。',
      firstLook: '固定一个 seed 与三组参数，检查输出是否可复现、交互是否可用，以及是否存在外部资源依赖。',
      auditNote: '明确要求原创算法艺术并避免复刻在世艺术家；许可仍需按仓库 LICENSE.txt 单独确认。',
      skillUrl: 'https://github.com/anthropics/skills/blob/main/skills/algorithmic-art/SKILL.md',
    },
  },
  {
    title: 'MCP Builder',
    slug: 'awesome-skill-anthropic-mcp-builder',
    summary: '围绕工具发现、分页、错误恢复与真实任务设计 MCP Server。',
    websiteUrl: 'https://github.com/anthropics/skills/tree/main/skills/mcp-builder',
    sourceUrl: 'https://github.com/anthropics/skills',
    sortOrder: 30,
    dossier: {
      schema: AWESOME_SKILL_SCHEMA,
      upstreamName: 'anthropics/skills · mcp-builder',
      category: 'agents',
      kinds: ['instructions', 'scripts', 'mcp'],
      compatibility: ['claude', 'generic'],
      permissions: ['filesystem', 'network', 'shell', 'credentials'],
      maturity: 'collected',
      effort: 'half-day',
      license: 'CUSTOM TERMS · REVIEW LICENSE.txt',
      licenseStatus: 'review',
      artifact: 'MCP SERVER PROTOTYPE',
      whyItMatters: '它关注工具是否真能被模型发现和组合，而不只是在 API 外面机械包一层协议。',
      firstLook: '拿一个只读 API 做最小 server，验证工具命名、分页、错误信息和凭据隔离，不先接生产写操作。',
      auditNote: '可能读取网络与凭据并执行本地命令；试用时必须使用最小权限测试账户和独立环境。',
      skillUrl: 'https://github.com/anthropics/skills/blob/main/skills/mcp-builder/SKILL.md',
    },
  },
  {
    title: 'PPTX Studio',
    slug: 'awesome-skill-anthropic-pptx',
    summary: '创建、读取、编辑和验证 PPTX，并把版式问题纳入可视化检查。',
    websiteUrl: 'https://github.com/anthropics/skills/tree/main/skills/pptx',
    sourceUrl: 'https://github.com/anthropics/skills',
    sortOrder: 40,
    dossier: {
      schema: AWESOME_SKILL_SCHEMA,
      upstreamName: 'anthropics/skills · pptx',
      category: 'creation',
      kinds: ['instructions', 'scripts', 'assets', 'templates'],
      compatibility: ['claude', 'generic'],
      permissions: ['filesystem', 'shell'],
      maturity: 'collected',
      effort: 'half-day',
      license: 'PROPRIETARY · REVIEW LICENSE.txt',
      licenseStatus: 'restricted',
      artifact: 'VALIDATED SLIDE DECK',
      whyItMatters: 'PPT 不是纯文本任务；它把模板继承、XML 修改、渲染和结构验证组合成可检查的交付链。',
      firstLook: '只用一份副本制作三页测试稿，完成结构校验、缩略图检查和 PDF 渲染，不覆盖原文件。',
      auditNote: 'frontmatter 明确标注 Proprietary；仅作为能力线索收录，未确认条款前不复制或再分发资源。',
      skillUrl: 'https://github.com/anthropics/skills/blob/main/skills/pptx/SKILL.md',
    },
  },
  {
    title: 'Skill Creator',
    slug: 'awesome-skill-openai-skill-creator',
    summary: '把可复用流程封装成具有渐进披露、资源与触发边界的 Codex Skill。',
    websiteUrl: 'https://github.com/openai/skills/tree/main/skills/.system/skill-creator',
    sourceUrl: 'https://github.com/openai/skills',
    sortOrder: 50,
    dossier: {
      schema: AWESOME_SKILL_SCHEMA,
      upstreamName: 'openai/skills · skill-creator',
      category: 'agents',
      kinds: ['instructions', 'scripts', 'templates'],
      compatibility: ['codex'],
      permissions: ['filesystem', 'shell'],
      maturity: 'collected',
      effort: '30-min',
      license: 'NOASSERTION · REVIEW REPOSITORY TERMS',
      licenseStatus: 'review',
      artifact: 'VALIDATED SKILL PACKAGE',
      whyItMatters: '它能把一次成功对话压缩成可重复能力，同时约束触发条件和上下文成本。',
      firstLook: '用一个已有小流程制作测试 Skill，检查 frontmatter、目录结构、资源引用和显式触发是否准确。',
      auditNote: '来源为 OpenAI 官方 Skill Catalog；GitHub license 元数据未给出 SPDX，需要逐项检查仓库条款。',
      skillUrl: 'https://github.com/openai/skills/blob/main/skills/.system/skill-creator/SKILL.md',
    },
  },
  {
    title: 'Playwright',
    slug: 'awesome-skill-openai-playwright',
    summary: '从终端驱动真实浏览器，完成导航、表单、截图、抽取和 UI 流程调试。',
    websiteUrl: 'https://github.com/openai/skills/tree/main/skills/.curated/playwright',
    sourceUrl: 'https://github.com/openai/skills',
    sortOrder: 60,
    dossier: {
      schema: AWESOME_SKILL_SCHEMA,
      upstreamName: 'openai/skills · playwright',
      category: 'engineering',
      kinds: ['instructions', 'scripts'],
      compatibility: ['codex'],
      permissions: ['filesystem', 'network', 'shell'],
      maturity: 'collected',
      effort: '30-min',
      license: 'NOASSERTION · REVIEW REPOSITORY TERMS',
      licenseStatus: 'review',
      artifact: 'BROWSER FLOW EVIDENCE',
      whyItMatters: '真实浏览器证据能暴露服务端渲染、交互、响应式和控制台问题，是视觉复刻与发布验收的基础。',
      firstLook: '在本地测试站跑一次只读旅程，保存桌面与移动截图并检查控制台，不登录真实第三方账户。',
      auditNote: '可访问网络、下载内容并驱动浏览器；探索外站前需明确授权范围，测试写操作必须隔离。',
      skillUrl: 'https://github.com/openai/skills/blob/main/skills/.curated/playwright/SKILL.md',
    },
  },
  {
    title: 'Security Threat Model',
    slug: 'awesome-skill-openai-security-threat-model',
    summary: '从真实仓库证据提取信任边界、资产、攻击路径与可执行缓解措施。',
    websiteUrl: 'https://github.com/openai/skills/tree/main/skills/.curated/security-threat-model',
    sourceUrl: 'https://github.com/openai/skills',
    sortOrder: 70,
    dossier: {
      schema: AWESOME_SKILL_SCHEMA,
      upstreamName: 'openai/skills · security-threat-model',
      category: 'engineering',
      kinds: ['instructions', 'templates'],
      compatibility: ['codex'],
      permissions: ['read-only', 'filesystem'],
      maturity: 'collected',
      effort: 'half-day',
      license: 'NOASSERTION · REVIEW REPOSITORY TERMS',
      licenseStatus: 'review',
      artifact: 'REPO-GROUNDED THREAT MODEL',
      whyItMatters: '它要求每条架构判断都有仓库证据，适合把笼统安全检查变成具体攻击路径和修复优先级。',
      firstLook: '先对一个小模块做只读威胁模型，核对边界、资产和入口是否都能落到文件与配置证据。',
      auditNote: '默认应只读；报告可能包含敏感拓扑与安全缺口，输出不可直接公开。',
      skillUrl: 'https://github.com/openai/skills/blob/main/skills/.curated/security-threat-model/SKILL.md',
    },
  },
  {
    title: 'Jupyter Notebook',
    slug: 'awesome-skill-openai-jupyter-notebook',
    summary: '以可复现结构创建或整理实验型、教程型 Jupyter Notebook。',
    websiteUrl: 'https://github.com/openai/skills/tree/main/skills/.curated/jupyter-notebook',
    sourceUrl: 'https://github.com/openai/skills',
    sortOrder: 80,
    dossier: {
      schema: AWESOME_SKILL_SCHEMA,
      upstreamName: 'openai/skills · jupyter-notebook',
      category: 'research',
      kinds: ['instructions', 'scripts', 'templates'],
      compatibility: ['codex'],
      permissions: ['filesystem', 'shell'],
      maturity: 'collected',
      effort: '30-min',
      license: 'NOASSERTION · REVIEW REPOSITORY TERMS',
      licenseStatus: 'review',
      artifact: 'REPRODUCIBLE NOTEBOOK',
      whyItMatters: '它适合把闲置算力变成可复跑实验，而不是只留下不可追踪的命令和截图。',
      firstLook: '从内置模板生成一份最小实验 Notebook，重启 kernel 后从头运行并确认无隐式状态依赖。',
      auditNote: 'Notebook 代码具有与脚本相同的执行风险；未知文件必须先检查 cell、外链和凭据读取。',
      skillUrl: 'https://github.com/openai/skills/blob/main/skills/.curated/jupyter-notebook/SKILL.md',
    },
  },
  {
    title: 'Web Design Guidelines',
    slug: 'awesome-skill-vercel-web-design-guidelines',
    summary: '按最新 Web Interface Guidelines 审查 UI、可访问性与交互实现。',
    websiteUrl: 'https://github.com/vercel-labs/agent-skills/tree/main/skills/web-design-guidelines',
    sourceUrl: 'https://github.com/vercel-labs/agent-skills',
    sortOrder: 90,
    dossier: {
      schema: AWESOME_SKILL_SCHEMA,
      upstreamName: 'vercel-labs/agent-skills · web-design-guidelines',
      category: 'design',
      kinds: ['instructions'],
      compatibility: ['codex', 'claude', 'generic'],
      permissions: ['read-only', 'network'],
      maturity: 'collected',
      effort: '5-min',
      license: 'MIT',
      licenseStatus: 'clear',
      artifact: 'LINE-LEVEL UI REVIEW',
      whyItMatters: '它从持续更新的规则源读取检查项，适合给完成后的界面做快速机械审查。',
      firstLook: '对一个组件与其样式文件运行审查，确认输出能落到具体文件行，并人工排除不适用规则。',
      auditNote: '每次会联网抓取最新指南；结果是检查线索，不替代真实渲染和键盘、读屏验收。',
      skillUrl: 'https://github.com/vercel-labs/agent-skills/blob/main/skills/web-design-guidelines/SKILL.md',
    },
  },
  {
    title: 'React Best Practices',
    slug: 'awesome-skill-vercel-react-best-practices',
    summary: '围绕瀑布、包体、服务端与重渲染成本优化 React 和 Next.js。',
    websiteUrl: 'https://github.com/vercel-labs/agent-skills/tree/main/skills/react-best-practices',
    sourceUrl: 'https://github.com/vercel-labs/agent-skills',
    sortOrder: 100,
    dossier: {
      schema: AWESOME_SKILL_SCHEMA,
      upstreamName: 'vercel-labs/agent-skills · react-best-practices',
      category: 'engineering',
      kinds: ['instructions'],
      compatibility: ['codex', 'claude', 'generic'],
      permissions: ['read-only', 'filesystem'],
      maturity: 'audited',
      effort: '30-min',
      license: 'MIT',
      licenseStatus: 'clear',
      artifact: 'PRIORITIZED PERFORMANCE PASS',
      whyItMatters: '它按影响排序性能规则，能先处理请求瀑布和包体等高收益问题，避免沉迷微优化。',
      firstLook: '先对一个 Next.js 路由做只读审查，只实施有测量证据的高影响项，再比较构建和运行结果。',
      auditNote: '本项目已完整读取其规则用于 React 实现约束，但尚未把该上游 Skill 作为独立自动化流程验证。',
      skillUrl: 'https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/SKILL.md',
    },
  },
  {
    title: 'React Composition Patterns',
    slug: 'awesome-skill-vercel-composition-patterns',
    summary: '用组合、compound components 与状态提升替代失控的 boolean props。',
    websiteUrl: 'https://github.com/vercel-labs/agent-skills/tree/main/skills/composition-patterns',
    sourceUrl: 'https://github.com/vercel-labs/agent-skills',
    sortOrder: 110,
    dossier: {
      schema: AWESOME_SKILL_SCHEMA,
      upstreamName: 'vercel-labs/agent-skills · composition-patterns',
      category: 'engineering',
      kinds: ['instructions'],
      compatibility: ['codex', 'claude', 'generic'],
      permissions: ['read-only', 'filesystem'],
      maturity: 'collected',
      effort: '30-min',
      license: 'MIT',
      licenseStatus: 'clear',
      artifact: 'COMPOSABLE COMPONENT API',
      whyItMatters: '它适合在组件 API 已经出现布尔参数爆炸时收敛复杂度，而不是提前创造抽象。',
      firstLook: '选择一个已有复杂组件，先记录真实调用方，再比较 compound component 改造是否减少分支和破坏面。',
      auditNote: '包含 React 19 相关建议；用于 React 18 项目时必须逐条核对版本适用性。',
      skillUrl: 'https://github.com/vercel-labs/agent-skills/blob/main/skills/composition-patterns/SKILL.md',
    },
  },
  {
    title: 'React View Transitions',
    slug: 'awesome-skill-vercel-react-view-transitions',
    summary: '用原生 View Transition API 表达页面、列表与共享元素之间的连续性。',
    websiteUrl: 'https://github.com/vercel-labs/agent-skills/tree/main/skills/react-view-transitions',
    sourceUrl: 'https://github.com/vercel-labs/agent-skills',
    sortOrder: 120,
    dossier: {
      schema: AWESOME_SKILL_SCHEMA,
      upstreamName: 'vercel-labs/agent-skills · react-view-transitions',
      category: 'design',
      kinds: ['instructions', 'templates'],
      compatibility: ['codex', 'claude', 'generic'],
      permissions: ['filesystem'],
      maturity: 'collected',
      effort: 'half-day',
      license: 'MIT',
      licenseStatus: 'clear',
      artifact: 'NATIVE MOTION PROTOTYPE',
      whyItMatters: '它把动效约束为信息关系，而不是给所有元素随意添加 hover 和淡入。',
      firstLook: '在一个独立列表到详情的 demo 中测试共享元素、前进后退与 reduced-motion，不直接改主导航。',
      auditNote: '依赖较新的 React 与浏览器能力；必须保留无动画回退并核对当前 Next.js 版本。',
      skillUrl: 'https://github.com/vercel-labs/agent-skills/blob/main/skills/react-view-transitions/SKILL.md',
    },
  },
  {
    title: 'Prompt Optimizer',
    slug: 'awesome-skill-github-prompt-optimizer',
    summary: '把粗糙想法整理为可以直接复制发送、没有占位符的完整 Prompt。',
    websiteUrl: 'https://github.com/github/awesome-copilot/tree/main/skills/prompt-optimizer',
    sourceUrl: 'https://github.com/github/awesome-copilot',
    sortOrder: 130,
    dossier: {
      schema: AWESOME_SKILL_SCHEMA,
      upstreamName: 'github/awesome-copilot · prompt-optimizer',
      category: 'agents',
      kinds: ['instructions'],
      compatibility: ['generic'],
      permissions: ['read-only'],
      maturity: 'collected',
      effort: '5-min',
      license: 'MIT REPOSITORY · VERIFY CONTRIBUTION',
      licenseStatus: 'clear',
      artifact: 'COPY-READY PROMPT',
      whyItMatters: '它和本站 Prompt 中心天然相邻，可作为“收集能力”与“可运行提示词”之间最轻量的桥。',
      firstLook: '用三条本站草稿比较优化前后正文，检查是否引入事实、占位符或过度结构化，再决定是否绑定 Workbench。',
      auditNote: '当前只收录，不绑定公开 Prompt，也不在 Skill Index 内运行；验证通过后再建立 promptSlug。',
      skillUrl: 'https://github.com/github/awesome-copilot/blob/main/skills/prompt-optimizer/SKILL.md',
    },
  },
  {
    title: 'Agentic Eval',
    slug: 'awesome-skill-github-agentic-eval',
    summary: '用 rubric、反思循环和 evaluator-optimizer 管线评估 Agent 输出。',
    websiteUrl: 'https://github.com/github/awesome-copilot/tree/main/skills/agentic-eval',
    sourceUrl: 'https://github.com/github/awesome-copilot',
    sortOrder: 140,
    dossier: {
      schema: AWESOME_SKILL_SCHEMA,
      upstreamName: 'github/awesome-copilot · agentic-eval',
      category: 'research',
      kinds: ['instructions', 'templates'],
      compatibility: ['generic'],
      permissions: ['read-only', 'filesystem'],
      maturity: 'collected',
      effort: 'half-day',
      license: 'MIT REPOSITORY · VERIFY CONTRIBUTION',
      licenseStatus: 'clear',
      artifact: 'EVALUATION LOOP',
      whyItMatters: '它能把“看起来不错”转为明确 rubric 与迭代证据，适合提示词和 Agent 输出的质量研究。',
      firstLook: '选一项可判定任务建立小 rubric，对比单次输出与一次改进循环，记录成本、偏差与失败样本。',
      auditNote: 'LLM-as-judge 会继承模型偏差；必须保存原始输出、判据和人工抽检，不能把分数当绝对真值。',
      skillUrl: 'https://github.com/github/awesome-copilot/blob/main/skills/agentic-eval/SKILL.md',
    },
  },
  {
    title: 'Slang Shader Engineer',
    slug: 'awesome-skill-github-slang-shader-engineer',
    summary: '编写、审查和优化可跨图形 API 编译的 Slang Shader 与 GPU 管线。',
    websiteUrl: 'https://github.com/github/awesome-copilot/tree/main/skills/slang-shader-engineer',
    sourceUrl: 'https://github.com/github/awesome-copilot',
    sortOrder: 150,
    dossier: {
      schema: AWESOME_SKILL_SCHEMA,
      upstreamName: 'github/awesome-copilot · slang-shader-engineer',
      category: 'creation',
      kinds: ['instructions', 'assets'],
      compatibility: ['generic'],
      permissions: ['filesystem', 'shell'],
      maturity: 'collected',
      effort: 'half-day',
      license: 'MIT REPOSITORY · VERIFY CONTRIBUTION',
      licenseStatus: 'clear',
      artifact: 'CROSS-TARGET SHADER',
      whyItMatters: '它把空闲 GPU 算力连接到实时视觉、游戏渲染与计算图形，而不局限于图片模型。',
      firstLook: '编译一个最小 compute shader 到两种目标，记录输出一致性、编译器版本和硬件限制。',
      auditNote: '需要本地编译工具链与 GPU 能力；先在隔离 demo 中验证，不直接接入现有渲染器。',
      skillUrl: 'https://github.com/github/awesome-copilot/blob/main/skills/slang-shader-engineer/SKILL.md',
    },
  },
  {
    title: 'Arduino × Azure IoT Edge',
    slug: 'awesome-skill-github-arduino-azure-iot-edge',
    summary: '设计 Arduino 到 IoT Hub / Edge 的安全接入、缓冲、遥测与命令链。',
    websiteUrl: 'https://github.com/github/awesome-copilot/tree/main/skills/arduino-azure-iot-edge-integration',
    sourceUrl: 'https://github.com/github/awesome-copilot',
    sortOrder: 160,
    dossier: {
      schema: AWESOME_SKILL_SCHEMA,
      upstreamName: 'github/awesome-copilot · arduino-azure-iot-edge-integration',
      category: 'hardware',
      kinds: ['instructions', 'scripts', 'templates'],
      compatibility: ['generic'],
      permissions: ['filesystem', 'network', 'shell', 'credentials'],
      maturity: 'collected',
      effort: 'half-day',
      license: 'MIT REPOSITORY · VERIFY CONTRIBUTION',
      licenseStatus: 'clear',
      artifact: 'EDGE TELEMETRY DEMO',
      whyItMatters: '它让网站里的研究目标延伸到传感器、边缘计算与真实物理反馈，适合闲置开发板实践。',
      firstLook: '先用模拟遥测和测试凭据验证断网缓冲、重连与命令边界，再连接真实设备。',
      auditNote: '涉及云端凭据和设备控制；必须使用测试租户、最小权限与可撤销密钥，禁止直接接生产执行器。',
      skillUrl: 'https://github.com/github/awesome-copilot/blob/main/skills/arduino-azure-iot-edge-integration/SKILL.md',
    },
  },
  {
    title: 'DSH Find Simplifications',
    slug: 'awesome-skill-dsh-find-simplifications',
    summary: '为 DeepSeek Harness 找到有证据的净简化候选，并保留架构保护边界。',
    websiteUrl: 'https://github.com/deepseek-ai/deepseek-harness/tree/master/.agents/skills/dsh-find-simplifications',
    sourceUrl: 'https://github.com/deepseek-ai/deepseek-harness',
    sortOrder: 170,
    dossier: {
      schema: AWESOME_SKILL_SCHEMA,
      upstreamName: 'deepseek-ai/deepseek-harness · dsh-find-simplifications',
      category: 'engineering',
      kinds: ['instructions', 'templates'],
      compatibility: ['dsh'],
      permissions: ['read-only', 'filesystem'],
      maturity: 'audited',
      effort: 'half-day',
      license: 'MIT',
      licenseStatus: 'clear',
      artifact: 'EVIDENCE-BACKED SIMPLIFICATION NOTE',
      whyItMatters: '它把“代码太多”转为消费者、契约和历史证据，优先减少真实维护面而不是机械删行。',
      firstLook: '只在 deepseek-harness 仓库显式调用，先做只读审计并保留双适配器等受保护设计。',
      auditNote: '本站本地已安装为显式调用 Skill；它只适用于 deepseek-harness，不应自动触发普通重构。',
      skillUrl: 'https://github.com/deepseek-ai/deepseek-harness/blob/master/.agents/skills/dsh-find-simplifications/SKILL.md',
    },
  },
  {
    title: 'Image Generation',
    slug: 'awesome-skill-openai-imagegen',
    summary: '生成、编辑并派生可追溯的位图素材，覆盖插画、贴图、精灵、抠图与视觉方案。',
    websiteUrl: 'https://github.com/openai/skills/tree/main/skills/.system/imagegen',
    sourceUrl: 'https://github.com/openai/skills',
    sortOrder: 180,
    dossier: {
      schema: AWESOME_SKILL_SCHEMA,
      upstreamName: 'openai/skills · imagegen',
      category: 'creation',
      kinds: ['instructions', 'scripts', 'assets'],
      compatibility: ['codex'],
      permissions: ['filesystem', 'network', 'shell', 'credentials'],
      maturity: 'collected',
      effort: '30-min',
      license: 'NOASSERTION · REVIEW REPOSITORY TERMS',
      licenseStatus: 'review',
      artifact: 'TRACEABLE RASTER VARIANT',
      whyItMatters: '它把图片生成与编辑统一为明确模式，并要求项目素材离开临时目录前有稳定路径和版本名。',
      firstLook: '先用内置工具生成一张独立测试素材，保存原始提示、参考图和输出版本，不启用需要密钥的 CLI 回退。',
      auditNote: 'CLI 只允许显式启用且需要 OpenAI API Key；不能自动切换，也不能覆盖现有项目素材。',
      skillUrl: 'https://github.com/openai/skills/blob/main/skills/.system/imagegen/SKILL.md',
    },
  },
  {
    title: 'System Screenshot',
    slug: 'awesome-skill-openai-screenshot',
    summary: '在浏览器工具无法覆盖时，按屏幕、窗口或区域采集桌面级视觉证据。',
    websiteUrl: 'https://github.com/openai/skills/tree/main/skills/.curated/screenshot',
    sourceUrl: 'https://github.com/openai/skills',
    sortOrder: 190,
    dossier: {
      schema: AWESOME_SKILL_SCHEMA,
      upstreamName: 'openai/skills · screenshot',
      category: 'design',
      kinds: ['instructions', 'scripts', 'assets'],
      compatibility: ['codex'],
      permissions: ['filesystem', 'shell'],
      maturity: 'collected',
      effort: '5-min',
      license: 'NOASSERTION · REVIEW REPOSITORY TERMS',
      licenseStatus: 'review',
      artifact: 'OS-LEVEL CAPTURE EVIDENCE',
      whyItMatters: '完整桌面和原生应用无法总被浏览器测试覆盖，系统级截图能补上真实 UI 验收的证据缺口。',
      firstLook: '只截取一个无敏感信息的测试窗口，核对输出位置、像素尺寸和多屏选择，不默认截取整个桌面。',
      auditNote: '系统截图可能暴露通知、凭据或其他窗口；必须限制区域、使用临时目录并在交付前人工检查。',
      skillUrl: 'https://github.com/openai/skills/blob/main/skills/.curated/screenshot/SKILL.md',
    },
  },
  {
    title: 'PDF Render Review',
    slug: 'awesome-skill-openai-pdf',
    summary: '读取、生成并渲染检查 PDF，让排版质量和内容正确性同时可验证。',
    websiteUrl: 'https://github.com/openai/skills/tree/main/skills/.curated/pdf',
    sourceUrl: 'https://github.com/openai/skills',
    sortOrder: 200,
    dossier: {
      schema: AWESOME_SKILL_SCHEMA,
      upstreamName: 'openai/skills · pdf',
      category: 'creation',
      kinds: ['instructions', 'scripts', 'templates'],
      compatibility: ['codex'],
      permissions: ['filesystem', 'shell'],
      maturity: 'collected',
      effort: '30-min',
      license: 'NOASSERTION · REVIEW REPOSITORY TERMS',
      licenseStatus: 'review',
      artifact: 'RENDER-VERIFIED PDF',
      whyItMatters: 'PDF 的成功不能只靠文本抽取判断；逐页渲染能暴露溢出、字体、表格和分页问题。',
      firstLook: '从两页测试文档开始，分别做文本抽取和 PNG 渲染检查，确认依赖齐全后再处理真实文件副本。',
      auditNote: '可能安装 Python 包和 Poppler；未知 PDF 应先隔离读取，最终交付必须以真实渲染为准。',
      skillUrl: 'https://github.com/openai/skills/blob/main/skills/.curated/pdf/SKILL.md',
    },
  },
  {
    title: 'Speech Generation',
    slug: 'awesome-skill-openai-speech',
    summary: '用可复现参数生成旁白、无障碍朗读、产品演示配音和批量语音片段。',
    websiteUrl: 'https://github.com/openai/skills/tree/main/skills/.curated/speech',
    sourceUrl: 'https://github.com/openai/skills',
    sortOrder: 210,
    dossier: {
      schema: AWESOME_SKILL_SCHEMA,
      upstreamName: 'openai/skills · speech',
      category: 'creation',
      kinds: ['instructions', 'scripts', 'assets'],
      compatibility: ['codex'],
      permissions: ['filesystem', 'network', 'shell', 'credentials'],
      maturity: 'collected',
      effort: '30-min',
      license: 'NOASSERTION · REVIEW REPOSITORY TERMS',
      licenseStatus: 'review',
      artifact: 'VOICEOVER BATCH',
      whyItMatters: '它让音频提示词产出从一段描述变成带原文、声线、指令和参数的可重放交付。',
      firstLook: '用一段非敏感短文生成单个测试片段，检查发音、节奏、文件格式和最终参数，再尝试批量模式。',
      auditNote: '实时调用需要 API Key 并产生费用；不能克隆自定义声音，文本、声音权利和隐私需人工确认。',
      skillUrl: 'https://github.com/openai/skills/blob/main/skills/.curated/speech/SKILL.md',
    },
  },
  {
    title: 'Audio Transcription',
    slug: 'awesome-skill-openai-transcribe',
    summary: '把音频或视频转为文本，并可选择说话人分离和已知说话人提示。',
    websiteUrl: 'https://github.com/openai/skills/tree/main/skills/.curated/transcribe',
    sourceUrl: 'https://github.com/openai/skills',
    sortOrder: 220,
    dossier: {
      schema: AWESOME_SKILL_SCHEMA,
      upstreamName: 'openai/skills · transcribe',
      category: 'research',
      kinds: ['instructions', 'scripts'],
      compatibility: ['codex'],
      permissions: ['filesystem', 'network', 'shell', 'credentials'],
      maturity: 'collected',
      effort: '30-min',
      license: 'NOASSERTION · REVIEW REPOSITORY TERMS',
      licenseStatus: 'review',
      artifact: 'DIARIZED TRANSCRIPT',
      whyItMatters: '采访、会议和演示视频可以沉淀为可检索素材，并保留分段和说话人边界供人工校对。',
      firstLook: '用一段获授权的一分钟录音比较纯文本和说话人分离输出，人工核对姓名、时间段和错词。',
      auditNote: '音视频会发送到云端并需要 API Key；敏感录音、身份信息与保存期限必须先得到授权。',
      skillUrl: 'https://github.com/openai/skills/blob/main/skills/.curated/transcribe/SKILL.md',
    },
  },
  {
    title: 'Canvas Design',
    slug: 'awesome-skill-anthropic-canvas-design',
    summary: '先建立原创视觉哲学，再将其表达为以图形、空间和节奏为主的静态作品。',
    websiteUrl: 'https://github.com/anthropics/skills/tree/main/skills/canvas-design',
    sourceUrl: 'https://github.com/anthropics/skills',
    sortOrder: 230,
    dossier: {
      schema: AWESOME_SKILL_SCHEMA,
      upstreamName: 'anthropics/skills · canvas-design',
      category: 'design',
      kinds: ['instructions', 'assets', 'templates'],
      compatibility: ['claude', 'generic'],
      permissions: ['filesystem', 'shell'],
      maturity: 'collected',
      effort: 'half-day',
      license: 'CUSTOM TERMS · REVIEW LICENSE.txt',
      licenseStatus: 'review',
      artifact: 'STATIC VISUAL PHILOSOPHY',
      whyItMatters: '它适合把抽象审美方向变成可检查的 PNG 或 PDF，而不是停留在形容词和风格标签。',
      firstLook: '选一个原创主题先写短视觉宣言，再制作单页海报，检查图形占比、层级和版权边界。',
      auditNote: 'Skill 明确要求原创且避免复制在世艺术家；仓库资源受单独 LICENSE.txt 约束，商用前需复核。',
      skillUrl: 'https://github.com/anthropics/skills/blob/main/skills/canvas-design/SKILL.md',
    },
  },
  {
    title: 'Theme Factory',
    slug: 'awesome-skill-anthropic-theme-factory',
    summary: '用成套颜色与字体配方统一幻灯片、文档、报告和网页制品。',
    websiteUrl: 'https://github.com/anthropics/skills/tree/main/skills/theme-factory',
    sourceUrl: 'https://github.com/anthropics/skills',
    sortOrder: 240,
    dossier: {
      schema: AWESOME_SKILL_SCHEMA,
      upstreamName: 'anthropics/skills · theme-factory',
      category: 'design',
      kinds: ['instructions', 'assets', 'templates'],
      compatibility: ['claude', 'generic'],
      permissions: ['filesystem'],
      maturity: 'collected',
      effort: '30-min',
      license: 'CUSTOM TERMS · REVIEW LICENSE.txt',
      licenseStatus: 'review',
      artifact: 'PORTABLE THEME SPECIMEN',
      whyItMatters: '稳定的客户风格交付需要颜色、字体和应用规则成套保存，而不是每页重新猜测。',
      firstLook: '先查看主题样本并把一个主题应用到三页测试稿，检查字体可用性、对比度和跨媒介一致性。',
      auditNote: '预设主题和展示资源受单独 LICENSE.txt 约束；字体许可与客户品牌规范仍需逐项确认。',
      skillUrl: 'https://github.com/anthropics/skills/blob/main/skills/theme-factory/SKILL.md',
    },
  },
  {
    title: 'Web Artifacts Builder',
    slug: 'awesome-skill-anthropic-web-artifacts-builder',
    summary: '用 React、Tailwind 与组件库制作可打包为单文件的复杂交互式网页制品。',
    websiteUrl: 'https://github.com/anthropics/skills/tree/main/skills/web-artifacts-builder',
    sourceUrl: 'https://github.com/anthropics/skills',
    sortOrder: 250,
    dossier: {
      schema: AWESOME_SKILL_SCHEMA,
      upstreamName: 'anthropics/skills · web-artifacts-builder',
      category: 'creation',
      kinds: ['instructions', 'scripts', 'templates'],
      compatibility: ['claude', 'generic'],
      permissions: ['filesystem', 'network', 'shell'],
      maturity: 'collected',
      effort: 'half-day',
      license: 'CUSTOM TERMS · REVIEW LICENSE.txt',
      licenseStatus: 'review',
      artifact: 'SELF-CONTAINED WEB ARTIFACT',
      whyItMatters: '它能验证复杂页面如何在保留状态、路由和组件的同时收束成便于分享的单文件成果。',
      firstLook: '在隔离目录生成一个双页面小工具，检查依赖安装、打包体积、离线打开与基础交互。',
      auditNote: '初始化和打包脚本会安装依赖并执行 shell；产物面向 Claude Artifact，许可与运行环境需单独核对。',
      skillUrl: 'https://github.com/anthropics/skills/blob/main/skills/web-artifacts-builder/SKILL.md',
    },
  },
  {
    title: 'Web Game Engine',
    slug: 'awesome-skill-github-game-engine',
    summary: '围绕游戏循环、物理、碰撞、输入、音频和发布构建 2D 或 3D Web 游戏。',
    websiteUrl: 'https://github.com/github/awesome-copilot/tree/main/skills/game-engine',
    sourceUrl: 'https://github.com/github/awesome-copilot',
    sortOrder: 260,
    dossier: {
      schema: AWESOME_SKILL_SCHEMA,
      upstreamName: 'github/awesome-copilot · game-engine',
      category: 'creation',
      kinds: ['instructions', 'assets', 'templates'],
      compatibility: ['generic'],
      permissions: ['filesystem', 'network', 'shell'],
      maturity: 'collected',
      effort: 'half-day',
      license: 'MIT REPOSITORY · VERIFY CONTRIBUTION',
      licenseStatus: 'clear',
      artifact: 'PLAYABLE WEB GAME SLICE',
      whyItMatters: '它把游戏创意落实到可玩的循环、控制、碰撞和性能预算，而不是只生成一张概念图。',
      firstLook: '从无外部素材的单屏 2D 游戏开始，验证键鼠与触控、固定步长和碰撞，再决定是否引入框架。',
      auditNote: '模板覆盖多个引擎和网络能力；第三方素材、依赖许可和多人通信安全仍需分别审查。',
      skillUrl: 'https://github.com/github/awesome-copilot/blob/main/skills/game-engine/SKILL.md',
    },
  },
  {
    title: 'FreeCAD Scripts',
    slug: 'awesome-skill-github-freecad-scripts',
    summary: '用 FreeCAD Python API 创建参数化模型、宏、工作台工具和自动化导出。',
    websiteUrl: 'https://github.com/github/awesome-copilot/tree/main/skills/freecad-scripts',
    sourceUrl: 'https://github.com/github/awesome-copilot',
    sortOrder: 270,
    dossier: {
      schema: AWESOME_SKILL_SCHEMA,
      upstreamName: 'github/awesome-copilot · freecad-scripts',
      category: 'hardware',
      kinds: ['instructions', 'scripts', 'templates'],
      compatibility: ['generic'],
      permissions: ['filesystem', 'shell'],
      maturity: 'collected',
      effort: 'half-day',
      license: 'MIT REPOSITORY · VERIFY CONTRIBUTION',
      licenseStatus: 'clear',
      artifact: 'PARAMETRIC CAD MODEL',
      whyItMatters: '参数化 CAD 能把设备外壳、支架和机械结构变成可修改、可重复导出的真实硬件资产。',
      firstLook: '先在新文档生成一个带尺寸参数的简单支架，检查单位、约束、重算和 STEP 导出。',
      auditNote: '宏可修改本地 CAD 文档并调用 FreeCAD 模块；始终在副本执行并记录应用与 API 版本。',
      skillUrl: 'https://github.com/github/awesome-copilot/blob/main/skills/freecad-scripts/SKILL.md',
    },
  },
  {
    title: 'Legacy Circuit Mockups',
    slug: 'awesome-skill-github-legacy-circuit-mockups',
    summary: '用 HTML Canvas 绘制面包板、复古芯片、无源器件和连线布局。',
    websiteUrl: 'https://github.com/github/awesome-copilot/tree/main/skills/legacy-circuit-mockups',
    sourceUrl: 'https://github.com/github/awesome-copilot',
    sortOrder: 280,
    dossier: {
      schema: AWESOME_SKILL_SCHEMA,
      upstreamName: 'github/awesome-copilot · legacy-circuit-mockups',
      category: 'hardware',
      kinds: ['instructions', 'assets', 'templates'],
      compatibility: ['generic'],
      permissions: ['filesystem'],
      maturity: 'collected',
      effort: 'half-day',
      license: 'MIT REPOSITORY · VERIFY CONTRIBUTION',
      licenseStatus: 'clear',
      artifact: 'BREADBOARD VISUAL PROTOTYPE',
      whyItMatters: '在接真实开发板前先得到可读的元件与连线图，适合复古计算和电子教学的视觉规划。',
      firstLook: '从 555 LED 闪烁电路开始，对照数据手册逐针检查，再让熟悉电路的人复核供电与极性。',
      auditNote: '生成的是视觉 mockup，不是电气仿真或安全认证；不能据此直接给高压或昂贵硬件上电。',
      skillUrl: 'https://github.com/github/awesome-copilot/blob/main/skills/legacy-circuit-mockups/SKILL.md',
    },
  },
  {
    title: 'Autoresearch Loop',
    slug: 'awesome-skill-github-autoresearch',
    summary: '围绕可量化指标自动修改、测量、保留或回退实验，形成持续优化记录。',
    websiteUrl: 'https://github.com/github/awesome-copilot/tree/main/skills/autoresearch',
    sourceUrl: 'https://github.com/github/awesome-copilot',
    sortOrder: 290,
    dossier: {
      schema: AWESOME_SKILL_SCHEMA,
      upstreamName: 'github/awesome-copilot · autoresearch',
      category: 'research',
      kinds: ['instructions', 'scripts', 'templates'],
      compatibility: ['generic'],
      permissions: ['filesystem', 'shell'],
      maturity: 'collected',
      effort: 'half-day',
      license: 'MIT',
      licenseStatus: 'clear',
      artifact: 'MEASURED EXPERIMENT LEDGER',
      whyItMatters: '它能把闲置算力转成基于指标的连续实验，并明确记录哪些改动提升、无效或退化。',
      firstLook: '只在隔离分支选择一个可快速测量的小指标，建立基线和修改范围，先运行三轮再审查日志。',
      auditNote: 'Skill 会提交实验并用 Git 回退失败改动；没有明确范围、基线和可恢复分支时绝不能启动。',
      skillUrl: 'https://github.com/github/awesome-copilot/blob/main/skills/autoresearch/SKILL.md',
    },
  },
  {
    title: 'Evidence Map',
    slug: 'awesome-skill-github-build-evidence-map',
    summary: '把支持、反驳、限定与未知证据组织成可验证的决策图，而非压平为结论。',
    websiteUrl: 'https://github.com/github/awesome-copilot/tree/main/skills/build-evidence-map',
    sourceUrl: 'https://github.com/github/awesome-copilot',
    sortOrder: 300,
    dossier: {
      schema: AWESOME_SKILL_SCHEMA,
      upstreamName: 'github/awesome-copilot · build-evidence-map',
      category: 'research',
      kinds: ['instructions', 'scripts', 'templates'],
      compatibility: ['generic'],
      permissions: ['read-only', 'filesystem', 'network', 'shell'],
      maturity: 'collected',
      effort: 'half-day',
      license: 'MIT REPOSITORY · VERIFY CONTRIBUTION',
      licenseStatus: 'clear',
      artifact: 'VALIDATED EVIDENCE MAP',
      whyItMatters: '复杂技术选择需要保留反证、范围差异和未知项，避免研究过程被一个顺滑段落掩盖。',
      firstLook: '对一个小型技术选型记录五个来源区域，生成并通过本地 validator，再人工核对每条边的语义。',
      auditNote: '网络快照验证只能显式授权后执行；没有确定性 VALID receipt 时不得声称证据图有效。',
      skillUrl: 'https://github.com/github/awesome-copilot/blob/main/skills/build-evidence-map/SKILL.md',
    },
  },
  {
    title: 'Automate This',
    slug: 'awesome-skill-github-automate-this',
    summary: '从手工操作录屏重建流程，并按复杂度生成可工作的自动化脚本。',
    websiteUrl: 'https://github.com/github/awesome-copilot/tree/main/skills/automate-this',
    sourceUrl: 'https://github.com/github/awesome-copilot',
    sortOrder: 310,
    dossier: {
      schema: AWESOME_SKILL_SCHEMA,
      upstreamName: 'github/awesome-copilot · automate-this',
      category: 'agents',
      kinds: ['instructions', 'scripts', 'templates'],
      compatibility: ['generic'],
      permissions: ['filesystem', 'network', 'shell', 'credentials'],
      maturity: 'collected',
      effort: 'half-day',
      license: 'MIT REPOSITORY · VERIFY CONTRIBUTION',
      licenseStatus: 'clear',
      artifact: 'RECORDING-DERIVED AUTOMATION',
      whyItMatters: '它能把真实重复劳动从录屏转换为脚本候选，比只凭口述猜测操作路径更接近可落地自动化。',
      firstLook: '录制一个只涉及测试文件的两分钟流程，检查抽帧、转写和步骤还原，再选择最低风险自动化层级。',
      auditNote: '录屏可能含账号和客户数据，生成脚本也可能写外部系统；必须脱敏、限制临时目录和显式授权写操作。',
      skillUrl: 'https://github.com/github/awesome-copilot/blob/main/skills/automate-this/SKILL.md',
    },
  },
  {
    title: 'AI Team Orchestration',
    slug: 'awesome-skill-github-ai-team-orchestration',
    summary: '以 Producer、Dev 和可选 QA 组织轻量多 Agent 项目执行与上下文交接。',
    websiteUrl: 'https://github.com/github/awesome-copilot/tree/main/skills/ai-team-orchestration',
    sourceUrl: 'https://github.com/github/awesome-copilot',
    sortOrder: 320,
    dossier: {
      schema: AWESOME_SKILL_SCHEMA,
      upstreamName: 'github/awesome-copilot · ai-team-orchestration',
      category: 'agents',
      kinds: ['instructions', 'templates'],
      compatibility: ['generic'],
      permissions: ['filesystem', 'network', 'shell'],
      maturity: 'collected',
      effort: 'half-day',
      license: 'MIT REPOSITORY · VERIFY CONTRIBUTION',
      licenseStatus: 'clear',
      artifact: 'BOUNDED MULTI-AGENT SPRINT',
      whyItMatters: '它把并行协作限制在明确角色、验收和交接上，适合拆分有独立结果的大型实验。',
      firstLook: '选一个可分为实现与独立 QA 的小任务，明确文件归属和合并策略，比较单 Agent 的时间与冲突成本。',
      auditNote: '多 Agent 不等于自动获得提交、推送或合并权限；必须继承仓库安全规则并避免并行修改同一文件。',
      skillUrl: 'https://github.com/github/awesome-copilot/blob/main/skills/ai-team-orchestration/SKILL.md',
    },
  },
  {
    title: 'Agent Supply Chain',
    slug: 'awesome-skill-github-agent-supply-chain',
    summary: '为 Agent 插件、工具和依赖生成哈希清单，检查篡改、版本固定与晋级来源。',
    websiteUrl: 'https://github.com/github/awesome-copilot/tree/main/skills/agent-supply-chain',
    sourceUrl: 'https://github.com/github/awesome-copilot',
    sortOrder: 330,
    dossier: {
      schema: AWESOME_SKILL_SCHEMA,
      upstreamName: 'github/awesome-copilot · agent-supply-chain',
      category: 'engineering',
      kinds: ['instructions', 'scripts', 'templates'],
      compatibility: ['generic'],
      permissions: ['read-only', 'filesystem', 'shell'],
      maturity: 'collected',
      effort: '30-min',
      license: 'MIT REPOSITORY · VERIFY CONTRIBUTION',
      licenseStatus: 'clear',
      artifact: 'INTEGRITY MANIFEST',
      whyItMatters: 'Skill 与 MCP 进入本机后具有真实权限，完整性清单能为试用、晋级和发布建立最小来源证据。',
      firstLook: '对一个无秘密的小型插件目录生成 SHA-256 manifest，修改副本后验证差异，再检查依赖是否固定版本。',
      auditNote: '文件哈希只能证明内容一致，不能替代签名、作者身份、依赖漏洞扫描或运行时沙箱。',
      skillUrl: 'https://github.com/github/awesome-copilot/blob/main/skills/agent-supply-chain/SKILL.md',
    },
  },
  {
    title: 'Illustrator Scripting',
    slug: 'awesome-skill-github-adobe-illustrator-scripting',
    summary: '用 ExtendScript 自动操作 Illustrator 文档、图层、路径、文字、画板和批量导出。',
    websiteUrl: 'https://github.com/github/awesome-copilot/tree/main/skills/adobe-illustrator-scripting',
    sourceUrl: 'https://github.com/github/awesome-copilot',
    sortOrder: 340,
    dossier: {
      schema: AWESOME_SKILL_SCHEMA,
      upstreamName: 'github/awesome-copilot · adobe-illustrator-scripting',
      category: 'creation',
      kinds: ['instructions', 'scripts', 'assets'],
      compatibility: ['generic'],
      permissions: ['filesystem', 'shell'],
      maturity: 'collected',
      effort: 'half-day',
      license: 'MIT REPOSITORY · VERIFY CONTRIBUTION',
      licenseStatus: 'clear',
      artifact: 'DATA-DRIVEN JSX ARTWORK',
      whyItMatters: '它能把矢量素材的尺寸、颜色、文字和导出规则变成可批量复用的生产脚本。',
      firstLook: '在 Illustrator 测试文档中生成三个简单画板并导出 SVG/PNG，检查坐标、单位和文件命名。',
      auditNote: '需要合法安装 Illustrator，JSX 会直接修改打开的文档；必须使用副本并限制文件与导出目录。',
      skillUrl: 'https://github.com/github/awesome-copilot/blob/main/skills/adobe-illustrator-scripting/SKILL.md',
    },
  },
  {
    title: 'Penpot UI/UX Design',
    slug: 'awesome-skill-github-penpot-uiux-design',
    summary: '通过 Penpot MCP 创建界面、组件、设计 token，并导出图形做可视化检查。',
    websiteUrl: 'https://github.com/github/awesome-copilot/tree/main/skills/penpot-uiux-design',
    sourceUrl: 'https://github.com/github/awesome-copilot',
    sortOrder: 350,
    dossier: {
      schema: AWESOME_SKILL_SCHEMA,
      upstreamName: 'github/awesome-copilot · penpot-uiux-design',
      category: 'design',
      kinds: ['instructions', 'scripts', 'mcp', 'templates'],
      compatibility: ['generic'],
      permissions: ['filesystem', 'network', 'shell', 'credentials'],
      maturity: 'collected',
      effort: 'half-day',
      license: 'MIT REPOSITORY · VERIFY CONTRIBUTION',
      licenseStatus: 'clear',
      artifact: 'INSPECTABLE PENPOT SYSTEM',
      whyItMatters: '它把开放设计工具、组件系统与代码执行连接起来，适合研究可交接的客户 UI 风格能力。',
      firstLook: '先连接隔离的 Penpot 测试文件，创建颜色 token、按钮组件和单屏布局，再导出 PNG/SVG 检查。',
      auditNote: 'MCP 可在 Penpot 上下文执行 JavaScript；安装、连接和写入必须得到确认并使用测试文件与最小凭据。',
      skillUrl: 'https://github.com/github/awesome-copilot/blob/main/skills/penpot-uiux-design/SKILL.md',
    },
  },
  {
    title: 'Continual Learning',
    slug: 'awesome-skill-microsoft-continual-learning',
    summary: '用 hook、分层记忆和反思循环让 Agent 在跨会话中保留可审查的经验。',
    websiteUrl: 'https://github.com/microsoft/skills/tree/main/.github/skills/continual-learning',
    sourceUrl: 'https://github.com/microsoft/skills',
    sortOrder: 360,
    dossier: {
      schema: AWESOME_SKILL_SCHEMA,
      upstreamName: 'microsoft/skills · continual-learning',
      category: 'agents',
      kinds: ['instructions', 'scripts', 'templates'],
      compatibility: ['generic'],
      permissions: ['filesystem', 'shell'],
      maturity: 'collected',
      effort: 'half-day',
      license: 'MIT',
      licenseStatus: 'clear',
      artifact: 'SCOPED LEARNING LOOP',
      whyItMatters: '持续学习能减少重复踩坑，但只有区分全局与项目记忆、保留人工审查时才不会放大错误经验。',
      firstLook: '在测试仓库安装本地层 hook，制造一次可识别失败并观察下次会话提示，再检查 SQLite 和记忆文件内容。',
      auditNote: 'Hook 会观察工具结果并写入本地或全局记忆；启用前需备份、限定范围并审查敏感信息与错误归因。',
      skillUrl: 'https://github.com/microsoft/skills/blob/main/.github/skills/continual-learning/SKILL.md',
    },
  },
  {
    title: 'Podcast Generation',
    slug: 'awesome-skill-microsoft-podcast-generation',
    summary: '用 Azure OpenAI Realtime WebSocket 把内容生成带转写的播客式音频。',
    websiteUrl: 'https://github.com/microsoft/skills/tree/main/.github/skills/podcast-generation',
    sourceUrl: 'https://github.com/microsoft/skills',
    sortOrder: 370,
    dossier: {
      schema: AWESOME_SKILL_SCHEMA,
      upstreamName: 'microsoft/skills · podcast-generation',
      category: 'creation',
      kinds: ['instructions', 'scripts', 'templates'],
      compatibility: ['generic'],
      permissions: ['filesystem', 'network', 'shell', 'credentials'],
      maturity: 'collected',
      effort: 'half-day',
      license: 'MIT',
      licenseStatus: 'clear',
      artifact: 'STREAMED PODCAST PROTOTYPE',
      whyItMatters: '它把内容整理、实时语音、PCM 转换和前端播放连接成一条可演示的音频生产链。',
      firstLook: '在 Azure 测试资源中用公开短文生成一分钟音频，核对转写、WAV 封装、延迟和费用。',
      auditNote: '需要 Azure 凭据并会产生云端费用；客户内容、音色权利、日志保存和公开发布都需单独授权。',
      skillUrl: 'https://github.com/microsoft/skills/blob/main/.github/skills/podcast-generation/SKILL.md',
    },
  },
  {
    title: 'Figma Screen Composer',
    slug: 'awesome-skill-openai-figma-generate-design',
    summary: '复用 Figma 组件、变量和样式，把页面描述或现有代码组装成可继续编辑的完整界面。',
    websiteUrl: 'https://github.com/openai/skills/tree/main/skills/.curated/figma-generate-design',
    sourceUrl: 'https://github.com/openai/skills',
    sortOrder: 380,
    dossier: {
      schema: AWESOME_SKILL_SCHEMA,
      upstreamName: 'openai/skills · figma-generate-design',
      category: 'design',
      kinds: ['instructions', 'mcp', 'templates'],
      compatibility: ['codex'],
      permissions: ['network', 'credentials'],
      maturity: 'collected',
      effort: 'half-day',
      license: 'NOASSERTION · REVIEW REPOSITORY TERMS',
      licenseStatus: 'review',
      artifact: 'TOKEN-BOUND FIGMA SCREEN',
      whyItMatters: '它优先复用发布中的设计系统，而不是硬画图元，适合把页面探索变成可交接、可持续维护的设计稿。',
      firstLook: '连接隔离的 Figma 测试文件，只组合一个已有组件与变量齐全的单屏，并逐段截图核对层级和约束。',
      auditNote: '它会通过 Figma MCP 写入远端文件且依赖配套 figma-use；必须使用测试副本、最小权限和明确写入范围。',
      skillUrl: 'https://github.com/openai/skills/blob/main/skills/.curated/figma-generate-design/SKILL.md',
    },
  },
  {
    title: 'Figma Design System Builder',
    slug: 'awesome-skill-openai-figma-generate-library',
    summary: '从代码抽取 token、主题和组件，在 Figma 中分阶段建立可维护的专业设计系统。',
    websiteUrl: 'https://github.com/openai/skills/tree/main/skills/.curated/figma-generate-library',
    sourceUrl: 'https://github.com/openai/skills',
    sortOrder: 390,
    dossier: {
      schema: AWESOME_SKILL_SCHEMA,
      upstreamName: 'openai/skills · figma-generate-library',
      category: 'design',
      kinds: ['instructions', 'mcp', 'templates'],
      compatibility: ['codex'],
      permissions: ['filesystem', 'network', 'credentials'],
      maturity: 'collected',
      effort: 'half-day',
      license: 'NOASSERTION · REVIEW REPOSITORY TERMS',
      licenseStatus: 'review',
      artifact: 'FIGMA DESIGN LIBRARY',
      whyItMatters: '它把颜色、间距、排版、模式和组件依赖按顺序建模，能减少设计稿与真实代码之间长期漂移。',
      firstLook: '先只读盘点一个测试项目与 Figma 文件，锁定最小 token 和按钮组件范围，经人工确认后再分阶段写入。',
      auditNote: '完整流程可能包含 20–100 次远端写入并维护本地状态；不可一键全量执行，也不能跳过阶段验收。',
      skillUrl: 'https://github.com/openai/skills/blob/main/skills/.curated/figma-generate-library/SKILL.md',
    },
  },
  {
    title: 'Figma-to-Code Fidelity',
    slug: 'awesome-skill-openai-figma-implement-design',
    summary: '读取 Figma 节点、截图和设计 token，把指定界面落成与现有组件体系一致的生产代码。',
    websiteUrl: 'https://github.com/openai/skills/tree/main/skills/.curated/figma-implement-design',
    sourceUrl: 'https://github.com/openai/skills',
    sortOrder: 400,
    dossier: {
      schema: AWESOME_SKILL_SCHEMA,
      upstreamName: 'openai/skills · figma-implement-design',
      category: 'design',
      kinds: ['instructions', 'mcp', 'assets'],
      compatibility: ['codex'],
      permissions: ['filesystem', 'network', 'shell', 'credentials'],
      maturity: 'collected',
      effort: 'half-day',
      license: 'NOASSERTION · REVIEW REPOSITORY TERMS',
      licenseStatus: 'review',
      artifact: 'FIDELITY-VERIFIED UI CODE',
      whyItMatters: '它要求把 Figma token 映射到项目 token，并用真实截图验证，适合研究设计到代码最后一公里的稳定做法。',
      firstLook: '选择一个无敏感内容的小组件，读取节点与截图后复用现有代码组件，最后做桌面和移动视觉对照。',
      auditNote: '会读取远端设计并修改本地代码、下载素材和运行验证；必须限定节点、目录与测试命令，避免覆盖用户改动。',
      skillUrl: 'https://github.com/openai/skills/blob/main/skills/.curated/figma-implement-design/SKILL.md',
    },
  },
  {
    title: 'Brand System',
    slug: 'awesome-skill-appautomaton-brand-system',
    summary: '把调研、色板、字体和风格方向沉淀为设计简报、机器配置与可视化预览。',
    websiteUrl: 'https://github.com/appautomaton/presentation/tree/main/brand-system',
    sourceUrl: 'https://github.com/appautomaton/presentation',
    sortOrder: 410,
    dossier: {
      schema: AWESOME_SKILL_SCHEMA,
      upstreamName: 'appautomaton/presentation · brand-system',
      category: 'design',
      kinds: ['instructions', 'scripts', 'assets', 'templates'],
      compatibility: ['codex', 'claude', 'generic'],
      permissions: ['filesystem', 'network', 'shell'],
      maturity: 'collected',
      effort: 'half-day',
      license: 'MIT',
      licenseStatus: 'clear',
      artifact: 'RENDERED BRAND SYSTEM',
      whyItMatters: '它让 PPT、文档和网站先共享同一套视觉语言，再进入生产阶段，避免每个产物临时拼一套风格。',
      firstLook: '从一个虚构品牌做三页预览，核对八角色色板、字体配对、对比度与下游 identity 配置是否一致。',
      auditNote: '会进行外部调研、安装依赖并写入工作目录；客户商标、字体授权和参考素材只能在明确授权范围内使用。',
      skillUrl: 'https://github.com/appautomaton/presentation/blob/main/brand-system/SKILL.md',
    },
  },
  {
    title: 'Consulting Storyboard',
    slug: 'awesome-skill-appautomaton-consultant',
    summary: '用假设驱动、金字塔结构与 action title 把业务问题变成可交给 PPT 制作的论证故事板。',
    websiteUrl: 'https://github.com/appautomaton/presentation/tree/main/consultant',
    sourceUrl: 'https://github.com/appautomaton/presentation',
    sortOrder: 420,
    dossier: {
      schema: AWESOME_SKILL_SCHEMA,
      upstreamName: 'appautomaton/presentation · consultant',
      category: 'creation',
      kinds: ['instructions', 'assets', 'templates'],
      compatibility: ['codex', 'claude', 'generic'],
      permissions: ['read-only', 'filesystem'],
      maturity: 'collected',
      effort: 'half-day',
      license: 'MIT',
      licenseStatus: 'clear',
      artifact: 'DECISION-LED STORYBOARD',
      whyItMatters: '高质量 PPT 首先是论证结构而不是模板；它能在画图前检查结论、支柱、证据和每页存在的必要性。',
      firstLook: '用一份公开业务案例生成十页以内故事板，只读 action title 做两分钟 helicopter test，再决定是否进入视觉制作。',
      auditNote: '框架不能替代事实核查，尤其是市场规模、财务和客户数据；外部结论必须带来源，未知数据不得补造。',
      skillUrl: 'https://github.com/appautomaton/presentation/blob/main/consultant/SKILL.md',
    },
  },
  {
    title: 'Native Deck Design',
    slug: 'awesome-skill-appautomaton-deck-design-ppt',
    summary: '把简报或故事板生成带母版、主题和原生可编辑对象的咨询级 PPTX。',
    websiteUrl: 'https://github.com/appautomaton/presentation/tree/main/deck-design-ppt',
    sourceUrl: 'https://github.com/appautomaton/presentation',
    sortOrder: 430,
    dossier: {
      schema: AWESOME_SKILL_SCHEMA,
      upstreamName: 'appautomaton/presentation · deck-design-ppt',
      category: 'creation',
      kinds: ['instructions', 'scripts', 'assets', 'templates'],
      compatibility: ['codex', 'claude', 'generic'],
      permissions: ['filesystem', 'network', 'shell'],
      maturity: 'collected',
      effort: 'half-day',
      license: 'MIT',
      licenseStatus: 'clear',
      artifact: 'NATIVE EDITABLE PPTX',
      whyItMatters: '它把 21 种版式、字符预算和空间约束编码进构建链，最终仍保留 PowerPoint 原生对象供客户继续修改。',
      firstLook: '用五页公开主题测试 cover、comparison、timeline 和 chart，完成内容溢出检查、缩略图巡检与实际 PPTX 打开验证。',
      auditNote: '需要安装 Node 依赖并执行构建脚本；输出中的事实、图标、字体许可与演示软件兼容性仍需逐项人工验收。',
      skillUrl: 'https://github.com/appautomaton/presentation/blob/main/deck-design-ppt/SKILL.md',
    },
  },
  {
    title: 'Pixel-perfect Deck PDF',
    slug: 'awesome-skill-appautomaton-deck-design-pdf',
    summary: '用 HTML、CSS、图表和 Playwright 生成高保真、适合展示与印刷的 PDF 演示稿。',
    websiteUrl: 'https://github.com/appautomaton/presentation/tree/main/deck-design-pdf',
    sourceUrl: 'https://github.com/appautomaton/presentation',
    sortOrder: 440,
    dossier: {
      schema: AWESOME_SKILL_SCHEMA,
      upstreamName: 'appautomaton/presentation · deck-design-pdf',
      category: 'creation',
      kinds: ['instructions', 'scripts', 'assets', 'templates'],
      compatibility: ['codex', 'claude', 'generic'],
      permissions: ['filesystem', 'network', 'shell'],
      maturity: 'collected',
      effort: 'half-day',
      license: 'MIT',
      licenseStatus: 'clear',
      artifact: 'PIXEL-PERFECT DECK PDF',
      whyItMatters: '当可编辑性不重要时，Web 排版能获得更强的字体、网格、渐变和图表表达，并可用真实渲染做逐页验收。',
      firstLook: '把同一份五页故事板同时交给 PDF 与 PPTX 路线，对比视觉精度、文本可读性、体积和后续编辑成本。',
      auditNote: '会运行浏览器与本地构建代码，可能加载网络字体；PDF 不是可编辑 PPTX，交付格式必须在开始前明确。',
      skillUrl: 'https://github.com/appautomaton/presentation/blob/main/deck-design-pdf/SKILL.md',
    },
  },
  {
    title: 'K-12 Lesson Planning',
    slug: 'awesome-skill-anthropic-k12-lesson-planning',
    summary: '从目标和课标出发，一次生成教案、学生材料与课堂观察模板，并保持内容同步。',
    websiteUrl: 'https://github.com/anthropics/k12-teacher-skills/tree/main/plugin/skills/k12-lesson-planning',
    sourceUrl: 'https://github.com/anthropics/k12-teacher-skills',
    sortOrder: 450,
    dossier: {
      schema: AWESOME_SKILL_SCHEMA,
      upstreamName: 'anthropics/k12-teacher-skills · k12-lesson-planning',
      category: 'creation',
      kinds: ['instructions', 'scripts', 'assets', 'templates'],
      compatibility: ['claude', 'generic'],
      permissions: ['filesystem', 'network', 'shell', 'credentials'],
      maturity: 'collected',
      effort: 'half-day',
      license: 'Apache-2.0',
      licenseStatus: 'clear',
      artifact: 'CLASSROOM-READY LESSON PACK',
      whyItMatters: '它不只写一段教案文本，而是把教学目标、活动、学生材料和观察证据组成可编辑且一致的课堂交付包。',
      firstLook: '用一节公开小学科学主题生成短课包，不连接外部知识图谱，检查目标、活动、退出任务和 Word 渲染是否一致。',
      auditNote: '默认课标体系偏美国 K-12；国内使用必须重新锚定课程标准，并人工复核年龄适配、事实、版权和课堂安全。',
      skillUrl: 'https://github.com/anthropics/k12-teacher-skills/blob/main/plugin/skills/k12-lesson-planning/SKILL.md',
    },
  },
  {
    title: 'K-12 Lesson Differentiation',
    slug: 'awesome-skill-anthropic-k12-lesson-differentiation',
    summary: '把已有课程改造成低于、符合和高于年级水平的分层材料，同时保持核心内容一致。',
    websiteUrl: 'https://github.com/anthropics/k12-teacher-skills/tree/main/plugin/skills/k12-lesson-differentiation',
    sourceUrl: 'https://github.com/anthropics/k12-teacher-skills',
    sortOrder: 460,
    dossier: {
      schema: AWESOME_SKILL_SCHEMA,
      upstreamName: 'anthropics/k12-teacher-skills · k12-lesson-differentiation',
      category: 'creation',
      kinds: ['instructions', 'scripts', 'assets', 'templates'],
      compatibility: ['claude', 'generic'],
      permissions: ['filesystem', 'network', 'shell', 'credentials'],
      maturity: 'collected',
      effort: 'half-day',
      license: 'Apache-2.0',
      licenseStatus: 'clear',
      artifact: 'THREE-TIER LESSON PACK',
      whyItMatters: '它把同一学习目标拆成三种进入路径，并用共享内容源减少分层材料在事实、题目和评价标准上的漂移。',
      firstLook: '提供一份自有短教案，生成三个层级的学生材料，逐项检查认知目标是否一致且脚手架没有替代核心学习。',
      auditNote: '涉及学生需求、IEP 或语言水平时会触及敏感教育信息；必须去标识化，并由教师审核公平性和适用性。',
      skillUrl: 'https://github.com/anthropics/k12-teacher-skills/blob/main/plugin/skills/k12-lesson-differentiation/SKILL.md',
    },
  },
]

export function awesomeSkillCandidateTags(skill: AwesomeSkillSeed): string[] {
  return [
    'awesome',
    'catalog:skill',
    `skill-category:${skill.dossier.category}`,
    `maturity:${skill.dossier.maturity}`,
    `license-status:${skill.dossier.licenseStatus}`,
    ...skill.dossier.kinds.map((kind) => `skill-kind:${kind}`),
    ...skill.dossier.compatibility.map((target) => `compatibility:${target}`),
    ...skill.dossier.permissions.map((permission) => `permission:${permission}`),
  ]
}

export function awesomeSkillDossierJson(skill: AwesomeSkillSeed): string {
  return JSON.stringify(skill.dossier)
}

export function backfillAwesomeSkillDossierJson(
  rawContent: string | null,
  skill: AwesomeSkillSeed,
): string | null {
  if (!rawContent) return null

  try {
    const parsed = JSON.parse(rawContent) as Record<string, unknown>
    if (parsed.schema !== AWESOME_SKILL_SCHEMA) return null

    const next = { ...parsed }
    let changed = false
    for (const key of [
      'category',
      'kinds',
      'compatibility',
      'permissions',
      'maturity',
      'effort',
      'licenseStatus',
      'artifact',
      'skillUrl',
    ] as const) {
      if (!(key in next)) {
        next[key] = skill.dossier[key]
        changed = true
      }
    }
    return changed ? JSON.stringify(next) : rawContent
  } catch {
    return null
  }
}

export function backfillAwesomeSkillTags(
  rawTags: string,
  skill: AwesomeSkillSeed,
): string | null {
  try {
    const parsed = JSON.parse(rawTags) as unknown
    if (!Array.isArray(parsed) || !parsed.every((tag) => typeof tag === 'string')) return null

    const next = [...parsed]
    for (const tag of awesomeSkillCandidateTags(skill)) {
      if (!next.includes(tag)) next.push(tag)
    }
    return next.length === parsed.length ? rawTags : JSON.stringify(next)
  } catch {
    return null
  }
}
