export const AWESOME_PROJECT_SCHEMA = 'awesome-project.v1'

export const AWESOME_DIRECTIONS = [
  { id: 'prompt-quality', label: 'PROMPT QUALITY' },
  { id: 'visual-production', label: 'VISUAL PRODUCTION' },
  { id: 'video-production', label: 'VIDEO PRODUCTION' },
  { id: 'audio-production', label: 'AUDIO PRODUCTION' },
  { id: 'three-d', label: '3D / SPATIAL' },
  { id: 'game-development', label: 'GAME DEVELOPMENT' },
  { id: 'embedded-systems', label: 'EMBEDDED SYSTEMS' },
  { id: 'robotics', label: 'ROBOTICS' },
  { id: 'model-infra', label: 'MODEL INFRA' },
  { id: 'developer-tools', label: 'DEVELOPER TOOLS' },
  { id: 'knowledge-tools', label: 'KNOWLEDGE TOOLS' },
  { id: 'design-systems', label: 'DESIGN SYSTEMS' },
  { id: 'presentation', label: 'PRESENTATION' },
  { id: 'self-hosted', label: 'SELF-HOSTED' },
  { id: 'science', label: 'SCIENCE' },
] as const

export type AwesomeDirection = (typeof AWESOME_DIRECTIONS)[number]['id']

export const AWESOME_READINESS = [
  { id: 'ready', label: 'READY' },
  { id: 'radar', label: 'RADAR' },
  { id: 'hold', label: 'HOLD' },
  { id: 'proven', label: 'PROVEN' },
] as const

export type AwesomeReadiness = (typeof AWESOME_READINESS)[number]['id']

export const AWESOME_COMPUTE_LEVELS = [
  { id: 'light', label: 'LIGHT' },
  { id: 'medium', label: 'MEDIUM' },
  { id: 'heavy', label: 'HEAVY' },
] as const

export type AwesomeComputeLevel = (typeof AWESOME_COMPUTE_LEVELS)[number]['id']

export type AwesomeLicenseStatus = 'clear' | 'review' | 'restricted'

export interface AwesomeProjectDossier {
  schema: typeof AWESOME_PROJECT_SCHEMA
  upstreamName: string
  direction: AwesomeDirection
  license: string
  licenseStatus: AwesomeLicenseStatus
  effort: string
  readiness: AwesomeReadiness
  compute: AwesomeComputeLevel
  artifact: string
  posture: 'BUILD' | 'INTEGRATE' | 'STUDY'
  whyItMatters: string
  buildProposal: string
  firstMilestone: string
  researchNote: string
}

export interface AwesomeProjectSeed {
  title: string
  slug: string
  summary: string
  websiteUrl: string
  sourceUrl: string
  sortOrder: number
  dossier: AwesomeProjectDossier
}

type AwesomeProjectDossierInput = Omit<
  AwesomeProjectDossier,
  'readiness' | 'compute' | 'artifact' | 'licenseStatus'
> & Partial<Pick<
  AwesomeProjectDossier,
  'readiness' | 'compute' | 'artifact' | 'licenseStatus'
>>

interface AwesomeProjectSeedInput extends Omit<AwesomeProjectSeed, 'dossier'> {
  dossier: AwesomeProjectDossierInput
}

function defineAwesomeProject(project: AwesomeProjectSeedInput): AwesomeProjectSeed {
  return {
    ...project,
    dossier: {
      readiness: 'radar',
      compute: 'medium',
      artifact: 'WORKING PROTOTYPE',
      licenseStatus: 'review',
      ...project.dossier,
    },
  }
}

export const AWESOME_DISCOVERY_FEEDS = [
  { name: 'AWESOME', scope: 'MASTER INDEX', url: 'https://github.com/sindresorhus/awesome' },
  { name: 'AWESOME SELFHOSTED', scope: 'LOCAL SERVICES', url: 'https://github.com/awesome-selfhosted/awesome-selfhosted' },
  { name: 'AWESOME GODOT', scope: 'GAME ECOSYSTEM', url: 'https://github.com/godotengine/awesome-godot' },
  { name: 'EMBEDDED RUST', scope: 'HARDWARE', url: 'https://github.com/rust-embedded/awesome-embedded-rust' },
] as const

const AWESOME_PROJECT_INPUTS: AwesomeProjectSeedInput[] = [
  {
    title: 'Prompt Regression Lab',
    slug: 'awesome-prompt-regression-lab',
    summary: '把“这个 Prompt 好像更好”变成可重复的模型 × 用例 × 断言对照实验。',
    websiteUrl: 'https://www.promptfoo.dev/',
    sourceUrl: 'https://github.com/promptfoo/promptfoo',
    sortOrder: 10,
    dossier: {
      schema: AWESOME_PROJECT_SCHEMA,
      upstreamName: 'promptfoo',
      direction: 'prompt-quality',
      license: 'MIT',
      licenseStatus: 'clear',
      readiness: 'ready',
      compute: 'light',
      artifact: 'EVALUATION MATRIX',
      effort: '3–5 DAYS',
      posture: 'INTEGRATE',
      whyItMatters: '当前工作台能运行 Prompt，但还不能稳定回答“哪一版、在哪个模型、对哪些样例更好”。',
      buildProposal: '把已验证 Prompt 一键生成本地 eval case，比较 DeepSeek、CPA 文本模型和后续图像评分器，并把结果写回版本链。',
      firstMilestone: '选择 3 个文本 Prompt、2 个模型、10 条固定样例，生成一张可追溯回归矩阵。',
      researchNote: '上游提供本地运行、模型对比、断言、CI 和结果导出；自定义脚本按受信代码处理。',
    },
  },
  {
    title: 'Prompt Evidence Ledger',
    slug: 'awesome-prompt-evidence-ledger',
    summary: '让每次运行都能回到 Prompt 版本、模型参数、输出、人工判断和发布决策。',
    websiteUrl: 'https://langfuse.com/',
    sourceUrl: 'https://github.com/langfuse/langfuse',
    sortOrder: 20,
    dossier: {
      schema: AWESOME_PROJECT_SCHEMA,
      upstreamName: 'Langfuse',
      direction: 'prompt-quality',
      license: 'MIT CORE / EE EXCEPTIONS',
      licenseStatus: 'review',
      readiness: 'radar',
      compute: 'medium',
      artifact: 'TRACE LEDGER',
      effort: '5–8 DAYS',
      posture: 'STUDY',
      whyItMatters: 'LogWood 已有 attribution 与版本链，但模型运行、人工选择和最终发布之间仍缺一张连续证据图。',
      buildProposal: '借鉴 trace、dataset、experiment 的数据语义，先在本站做轻量运行谱系，不直接搬入整个平台。',
      firstMilestone: '从一次 Workbench RUN 追到 Prompt 版本、模型、输出资产、人工评分和最终 Candidate。',
      researchNote: '上游覆盖可观测性、Prompt 管理、数据集和评估；核心 MIT，ee 目录另有条款。',
    },
  },
  {
    title: 'Style Recipe Engine',
    slug: 'awesome-style-recipe-engine',
    summary: '把画廊里的“风格印象”推进为可恢复、可复跑、可交付的节点配方。',
    websiteUrl: 'https://www.comfy.org/',
    sourceUrl: 'https://github.com/Comfy-Org/ComfyUI',
    sortOrder: 30,
    dossier: {
      schema: AWESOME_PROJECT_SCHEMA,
      upstreamName: 'ComfyUI',
      direction: 'visual-production',
      license: 'GPL-3.0',
      licenseStatus: 'clear',
      readiness: 'ready',
      compute: 'heavy',
      artifact: 'STYLE WORKFLOW PACK',
      effort: '7–12 DAYS',
      posture: 'INTEGRATE',
      whyItMatters: '客户出图真正需要的不是一张偶然好图，而是包含模型、seed、节点和后处理的稳定生成配方。',
      buildProposal: '让 Gallery 风格条目挂接只读 workflow JSON；由独立执行器运行，本站只保存来源、参数与结果，不加载不受信自定义节点。',
      firstMilestone: '为 3 种高频画风各固化 1 条工作流，并完成同题材三次复跑与差异记录。',
      researchNote: '上游支持图像、视频、音频、3D、文本节点图、局部重跑、API 和从媒体恢复 workflow/seed。',
    },
  },
  {
    title: 'Creative Canvas Bench',
    slug: 'awesome-creative-canvas-bench',
    summary: '研究从生成、局部修补、画布编排到素材归档的一体化专业创作流。',
    websiteUrl: 'https://invoke.ai/',
    sourceUrl: 'https://github.com/invoke-ai/InvokeAI',
    sortOrder: 40,
    dossier: {
      schema: AWESOME_PROJECT_SCHEMA,
      upstreamName: 'InvokeAI',
      direction: 'visual-production',
      license: 'APACHE-2.0',
      licenseStatus: 'clear',
      readiness: 'radar',
      compute: 'heavy',
      artifact: 'CANVAS INTERACTION STUDY',
      effort: '5–8 DAYS',
      posture: 'STUDY',
      whyItMatters: '单张预览不足以支撑客户交付；局部修改、版本回退、素材复用和元数据召回才是稳定生产能力。',
      buildProposal: '提炼 Unified Canvas 与 Gallery 的交互，把本站的效果预览升级成“结果 → 局部修改 → 版本候选”闭环。',
      firstMilestone: '做一个不含模型执行的画布原型：导入结果、建立 3 个局部修改候选、保留参数与回退点。',
      researchNote: '上游提供本地 Web UI、统一画布、节点工作流、图库管理和图像元数据召回。',
    },
  },
  {
    title: 'Capability-aware Model Router',
    slug: 'awesome-capability-model-router',
    summary: '按文本、图片、视频和能力约束选模型，在运行前就阻止“不支持生图”的错误。',
    websiteUrl: 'https://www.litellm.ai/',
    sourceUrl: 'https://github.com/BerriAI/litellm',
    sortOrder: 50,
    dossier: {
      schema: AWESOME_PROJECT_SCHEMA,
      upstreamName: 'LiteLLM',
      direction: 'model-infra',
      license: 'OSS / COMMERCIAL MODULES',
      licenseStatus: 'review',
      readiness: 'ready',
      compute: 'light',
      artifact: 'MODEL CAPABILITY MAP',
      effort: '3–5 DAYS',
      posture: 'STUDY',
      whyItMatters: '当前 DeepSeek 与 CPA 已经暴露模态差异；如果只按模型名选择，错误会在请求发出后才被发现。',
      buildProposal: '建立本站自己的 capability contract 与健康探测，借鉴统一 API、路由、成本和失败切换，不引入整套网关。',
      firstMilestone: '为现有 2 个 CPA 模型和 DeepSeek 输出能力卡，运行按钮按 output kind 只展示兼容模型。',
      researchNote: '上游以 OpenAI 兼容接口覆盖多供应商、图片/音频等端点，并提供路由、限额和日志能力；采用前需单独核对模块许可。',
    },
  },
  {
    title: 'Design-to-Code Style Lab',
    slug: 'awesome-design-to-code-style-lab',
    summary: '把网站风格从截图灵感变成 tokens、响应式结构和可交接的设计系统。',
    websiteUrl: 'https://penpot.app/',
    sourceUrl: 'https://github.com/penpot/penpot',
    sortOrder: 60,
    dossier: {
      schema: AWESOME_PROJECT_SCHEMA,
      upstreamName: 'Penpot',
      direction: 'design-systems',
      license: 'MPL-2.0',
      licenseStatus: 'clear',
      readiness: 'radar',
      compute: 'medium',
      artifact: 'DESIGN SYSTEM SPECIMEN',
      effort: '5–8 DAYS',
      posture: 'STUDY',
      whyItMatters: '网站风格能力如果只保存在效果截图里，很难验证响应式、token 一致性，也难向客户稳定复用。',
      buildProposal: '研究 design-as-code、原生 design token 和 MCP 的边界，为 Gallery 新增可下载的“视觉系统标本”。',
      firstMilestone: '选 2 个本站风格，分别导出颜色、字体、间距、组件状态和桌面/移动验收页。',
      researchNote: '上游强调 design-as-code、原生 design tokens、MCP、开放 API 与插件系统。',
    },
  },
  {
    title: 'UI Style Specimen Lab',
    slug: 'awesome-ui-style-specimen-lab',
    summary: '让每种网站风格都有真实组件、边界状态和视觉回归，而不只是一张首页图。',
    websiteUrl: 'https://storybook.js.org/',
    sourceUrl: 'https://github.com/storybookjs/storybook',
    sortOrder: 70,
    dossier: {
      schema: AWESOME_PROJECT_SCHEMA,
      upstreamName: 'Storybook',
      direction: 'design-systems',
      license: 'MIT',
      licenseStatus: 'clear',
      readiness: 'ready',
      compute: 'light',
      artifact: 'UI STATE MATRIX',
      effort: '3–5 DAYS',
      posture: 'INTEGRATE',
      whyItMatters: '客户网站的风格稳定性取决于按钮、表单、内容密度和异常态，而不是 Hero 单点效果。',
      buildProposal: '为本站常用 UI 语汇建立隔离标本，并接入桌面/移动截图回归，形成“我能稳定处理哪些网站风格”的证据。',
      firstMilestone: '完成 terminal、paper 两套主题下 8 个核心组件的状态矩阵与截图基线。',
      researchNote: '上游专注隔离构建、文档与测试 UI 组件，支持多框架和扩展插件。',
    },
  },
  {
    title: 'AI Deck Studio',
    slug: 'awesome-ai-deck-studio',
    summary: '把结构化内容 Prompt 转成可编辑、可换主题、可导出 PPTX/PDF 的演示文稿。',
    websiteUrl: 'https://sli.dev/',
    sourceUrl: 'https://github.com/slidevjs/slidev',
    sortOrder: 80,
    dossier: {
      schema: AWESOME_PROJECT_SCHEMA,
      upstreamName: 'Slidev',
      direction: 'presentation',
      license: 'MIT',
      licenseStatus: 'clear',
      readiness: 'ready',
      compute: 'light',
      artifact: 'EDITABLE DECK',
      effort: '5–8 DAYS',
      posture: 'INTEGRATE',
      whyItMatters: 'PPT 类 Prompt 的结果不能只显示文本；需要一个可编辑中间格式和可靠导出链，才能成为真实案例。',
      buildProposal: '让模型只生成受限 Markdown/组件 schema，再交给 Slidev 渲染；主题、素材与导出由人确认。',
      firstMilestone: '从一个客户 brief 生成 6 页 deck，支持主题切换、人工修改并导出 PDF/PPTX。',
      researchNote: '上游以 Markdown 驱动，支持主题、组件、图表、演讲模式和 PDF/PNG/PPTX 导出。',
    },
  },
  // Visual, video, 3D and audio production
  {
    title: 'Krita AI Diffusion Studio',
    slug: 'awesome-krita-ai-diffusion-studio',
    summary: '在成熟绘画软件里完成生成、局部修补、控制图和人工精修。',
    websiteUrl: 'https://krita-ai-diffusion.github.io/',
    sourceUrl: 'https://github.com/Acly/krita-ai-diffusion',
    sortOrder: 100,
    dossier: {
      schema: AWESOME_PROJECT_SCHEMA,
      upstreamName: 'Krita AI Diffusion',
      direction: 'visual-production',
      license: 'GPL-3.0',
      licenseStatus: 'clear',
      readiness: 'ready',
      compute: 'medium',
      artifact: 'EDITABLE IMAGE STUDY',
      effort: '1–2 DAYS',
      posture: 'INTEGRATE',
      whyItMatters: '它把一次性生图带回可控画布，适合验证客户出图时真正需要的局部修改链。',
      buildProposal: '建立一套从 LogWood 风格配方到 Krita/ComfyUI 工作流与最终素材的往返归档。',
      firstMilestone: '选择一张现有画廊图，完成局部换装、背景重绘和参数回存三步实验。',
      researchNote: '插件连接本地 ComfyUI；首次实验只使用官方节点与可核验模型，不加载陌生扩展。',
    },
  },
  {
    title: 'Wan Video Playground',
    slug: 'awesome-wan-video-playground',
    summary: '用开源视频模型建立文生视频、图生视频与镜头稳定性样本库。',
    websiteUrl: 'https://github.com/Wan-Video/Wan2.2',
    sourceUrl: 'https://github.com/Wan-Video/Wan2.2',
    sortOrder: 110,
    dossier: {
      schema: AWESOME_PROJECT_SCHEMA,
      upstreamName: 'Wan2.2',
      direction: 'video-production',
      license: 'APACHE-2.0 CODE / MODEL TERMS REVIEW',
      licenseStatus: 'review',
      readiness: 'ready',
      compute: 'heavy',
      artifact: 'VIDEO STYLE REEL',
      effort: '2–4 DAYS',
      posture: 'STUDY',
      whyItMatters: '视频提示词的稳定性只能通过固定镜头、动作和种子反复比较，截图无法替代。',
      buildProposal: '为 Gallery 增加短视频风格标本，记录模型、采样参数、帧率、时长和失败样本。',
      firstMilestone: '用同一首帧生成三段五秒视频，比较动作连续性、主体保持和时间成本。',
      researchNote: '模型权重体积与显存开销较大；启动前单独核对具体权重许可和硬件需求。',
    },
  },
  {
    title: 'LTX Motion Lab',
    slug: 'awesome-ltx-motion-lab',
    summary: '探索带音画同步、关键帧控制和 LoRA 的可编辑视频工作流。',
    websiteUrl: 'https://www.lightricks.com/ltxv',
    sourceUrl: 'https://github.com/Lightricks/LTX-Video',
    sortOrder: 120,
    dossier: {
      schema: AWESOME_PROJECT_SCHEMA,
      upstreamName: 'LTX-Video',
      direction: 'video-production',
      license: 'APACHE-2.0 CODE / MODEL TERMS REVIEW',
      licenseStatus: 'review',
      readiness: 'radar',
      compute: 'heavy',
      artifact: 'CONTROLLED MOTION STUDY',
      effort: '3–5 DAYS',
      posture: 'STUDY',
      whyItMatters: '音画同步与镜头控制更接近真实客户交付，也能补齐纯文生视频不可控的问题。',
      buildProposal: '研究关键帧、声音和风格 LoRA 如何固化为本站可展示、可复跑的视频配方。',
      firstMilestone: '完成一个十秒片段，至少包含首尾关键帧、环境声和一次局部重生成。',
      researchNote: '属于高算力实验；在下载权重前确认版本、模型条款和磁盘预算。',
    },
  },
  {
    title: 'FramePack Long-form Bench',
    slug: 'awesome-framepack-long-form-bench',
    summary: '用较低显存探索长视频生成，以及随时停止仍保留结果的实验方式。',
    websiteUrl: 'https://github.com/lllyasviel/FramePack',
    sourceUrl: 'https://github.com/lllyasviel/FramePack',
    sortOrder: 130,
    dossier: {
      schema: AWESOME_PROJECT_SCHEMA,
      upstreamName: 'FramePack',
      direction: 'video-production',
      license: 'APACHE-2.0',
      licenseStatus: 'clear',
      readiness: 'radar',
      compute: 'heavy',
      artifact: 'LONG VIDEO BENCHMARK',
      effort: '2–3 DAYS',
      posture: 'STUDY',
      whyItMatters: '它为显存有限但时间充足的机器提供另一条视频实验路径，符合闲时算力场景。',
      buildProposal: '记录不同片长下的速度、主体漂移和中断恢复表现，判断是否值得接入画廊。',
      firstMilestone: '固定一张输入图，生成三种时长并产出显存、耗时和稳定性对照表。',
      researchNote: '项目更新节奏与模型兼容性需要启动前复查，目前仅进入观察队列。',
    },
  },
  {
    title: 'TRELLIS Spatial Forge',
    slug: 'awesome-trellis-spatial-forge',
    summary: '把单张参考图转成带材质的 3D 资产，并检查是否能进入真实制作链。',
    websiteUrl: 'https://trellis2.github.io/',
    sourceUrl: 'https://github.com/microsoft/TRELLIS.2',
    sortOrder: 140,
    dossier: {
      schema: AWESOME_PROJECT_SCHEMA,
      upstreamName: 'TRELLIS.2',
      direction: 'three-d',
      license: 'MIT CODE / MODEL TERMS REVIEW',
      licenseStatus: 'review',
      readiness: 'ready',
      compute: 'heavy',
      artifact: 'PBR 3D ASSET',
      effort: '2–4 DAYS',
      posture: 'STUDY',
      whyItMatters: '如果输出能稳定进入 Blender 或游戏引擎，画廊就能从平面审美扩展到空间资产。',
      buildProposal: '建立参考图、提示词、生成网格、材质和人工修复记录之间的完整资产卡。',
      firstMilestone: '从三张不同题材参考图生成资产，检查拓扑、纹理、法线和导出兼容性。',
      researchNote: '高算力且模型文件较大；下载前确认权重条款，输出需人工检查拓扑质量。',
    },
  },
  {
    title: 'Hunyuan3D Asset Trial',
    slug: 'awesome-hunyuan3d-asset-trial',
    summary: '观察图生 3D 与纹理生成能力，先解决模型许可边界再做实验。',
    websiteUrl: 'https://3d.hunyuan.tencent.com/',
    sourceUrl: 'https://github.com/Tencent-Hunyuan/Hunyuan3D-2',
    sortOrder: 150,
    dossier: {
      schema: AWESOME_PROJECT_SCHEMA,
      upstreamName: 'Hunyuan3D-2',
      direction: 'three-d',
      license: 'TENCENT HUNYUAN COMMUNITY LICENSE',
      licenseStatus: 'restricted',
      readiness: 'hold',
      compute: 'heavy',
      artifact: '3D ASSET COMPARISON',
      effort: '2–4 DAYS',
      posture: 'STUDY',
      whyItMatters: '它适合作为 TRELLIS 的能力对照，但模型许可包含地域与使用条件，不能直接进入客户链。',
      buildProposal: '仅在许可确认后做同图对照实验，并明确把研究样本与可商用资产隔离。',
      firstMilestone: '完成许可清单与三组输入标准，不下载权重、不生成客户可用资产。',
      researchNote: '当前因模型许可进入 HOLD；任何下载、运行和商业使用都需再次核对最新条款。',
    },
  },
  {
    title: 'Blender Procedural Workshop',
    slug: 'awesome-blender-procedural-workshop',
    summary: '用程序化建模、几何节点和自动渲染把 AI 资产变成可控作品。',
    websiteUrl: 'https://www.blender.org/',
    sourceUrl: 'https://github.com/blender/blender',
    sortOrder: 160,
    dossier: {
      schema: AWESOME_PROJECT_SCHEMA,
      upstreamName: 'Blender',
      direction: 'three-d',
      license: 'GPL-3.0',
      licenseStatus: 'clear',
      readiness: 'ready',
      compute: 'medium',
      artifact: 'PROCEDURAL 3D SCENE',
      effort: '2–5 DAYS',
      posture: 'BUILD',
      whyItMatters: '生成模型只能给出原料，Blender 才能把尺寸、材质、灯光和交付格式收回人工控制。',
      buildProposal: '沉淀可复用的 Python/Geometry Nodes 小实验，展示本站能稳定处理的空间风格。',
      firstMilestone: '做一套参数化产品台，自动替换资产、灯光和相机并批量输出三种构图。',
      researchNote: '核心软件成熟；运行外部脚本时仍应只使用本站审计过的代码和隔离素材目录。',
    },
  },
  {
    title: 'OpenDroneMap Terrain Lab',
    slug: 'awesome-opendronemap-terrain-lab',
    summary: '把航拍照片转成正射影像、点云与三维地形，体验真实摄影测量链。',
    websiteUrl: 'https://www.opendronemap.org/',
    sourceUrl: 'https://github.com/OpenDroneMap/ODM',
    sortOrder: 170,
    dossier: {
      schema: AWESOME_PROJECT_SCHEMA,
      upstreamName: 'OpenDroneMap',
      direction: 'three-d',
      license: 'AGPL-3.0',
      licenseStatus: 'clear',
      readiness: 'radar',
      compute: 'heavy',
      artifact: 'PHOTOGRAMMETRY DATASET',
      effort: '2–4 DAYS',
      posture: 'STUDY',
      whyItMatters: '它把视觉算力用在可测量的现实数据上，能验证 3D、地图与工程展示的新方向。',
      buildProposal: '用公开小样本跑一条完整摄影测量流程，并将地图成果做成可交互案例。',
      firstMilestone: '处理一组公开航拍图，导出正射图、点云和低模并记录耗时与磁盘峰值。',
      researchNote: '需要大量 CPU、内存和磁盘；只使用授权清晰的公开数据集，避免位置与隐私风险。',
    },
  },
  {
    title: 'ACE-Step Music Bench',
    slug: 'awesome-ace-step-music-bench',
    summary: '测试开源音乐生成在风格、歌词、结构和可控编辑上的实际边界。',
    websiteUrl: 'https://github.com/ace-step/ACE-Step-1.5',
    sourceUrl: 'https://github.com/ace-step/ACE-Step-1.5',
    sortOrder: 180,
    dossier: {
      schema: AWESOME_PROJECT_SCHEMA,
      upstreamName: 'ACE-Step 1.5',
      direction: 'audio-production',
      license: 'CODE / MODEL TERMS REVIEW',
      licenseStatus: 'review',
      readiness: 'radar',
      compute: 'heavy',
      artifact: 'MUSIC STYLE REEL',
      effort: '2–4 DAYS',
      posture: 'STUDY',
      whyItMatters: '音乐提示词同样需要可比较的风格样本，而不是把“听起来不错”留在一次性体验里。',
      buildProposal: '建立音乐 Prompt、生成参数、结构标注和人工听感的轻量档案。',
      firstMilestone: '用同一歌词生成三种编曲，记录结构完整度、人声质量、耗时和许可信息。',
      researchNote: '启动前核对代码与具体模型权重许可，生成内容不得模仿在世艺人的可识别声音。',
    },
  },
  {
    title: 'Whisper Local Transcript',
    slug: 'awesome-whisper-local-transcript',
    summary: '在本地完成音视频转写、时间轴与字幕导出，作为创作素材入口。',
    websiteUrl: 'https://github.com/ggml-org/whisper.cpp',
    sourceUrl: 'https://github.com/ggml-org/whisper.cpp',
    sortOrder: 190,
    dossier: {
      schema: AWESOME_PROJECT_SCHEMA,
      upstreamName: 'whisper.cpp',
      direction: 'audio-production',
      license: 'MIT',
      licenseStatus: 'clear',
      readiness: 'ready',
      compute: 'light',
      artifact: 'SEARCHABLE TRANSCRIPT',
      effort: '0.5–1 DAY',
      posture: 'INTEGRATE',
      whyItMatters: '本地转写能把访谈、视频和灵感录音安全转成可检索内容，再进入 Prompt 与社区沉淀。',
      buildProposal: '做一个离线素材入口，输出带时间戳文本、字幕和来源哈希，不上传私人音频。',
      firstMilestone: '转写一段十分钟中英混合音频，比较 CPU/GPU 速度与字幕校正工作量。',
      researchNote: '适合轻量闲时任务；模型来源与输入素材权利仍需随档案记录。',
    },
  },
  {
    title: 'F5-TTS Voice Study',
    slug: 'awesome-f5-tts-voice-study',
    summary: '研究可控语音合成与参考音色，但不把非商用权重混入客户交付。',
    websiteUrl: 'https://swivid.github.io/F5-TTS/',
    sourceUrl: 'https://github.com/SWivid/F5-TTS',
    sortOrder: 200,
    dossier: {
      schema: AWESOME_PROJECT_SCHEMA,
      upstreamName: 'F5-TTS',
      direction: 'audio-production',
      license: 'MIT CODE / CC-BY-NC MODEL',
      licenseStatus: 'restricted',
      readiness: 'hold',
      compute: 'medium',
      artifact: 'NON-COMMERCIAL VOICE STUDY',
      effort: '1–2 DAYS',
      posture: 'STUDY',
      whyItMatters: '语音能补足视频与演示文稿，但预训练权重的非商用限制必须在产品层显式可见。',
      buildProposal: '只做研究标本和许可隔离设计，不接入面向客户的自动生成能力。',
      firstMilestone: '整理代码、权重、参考音频和输出的四层权利清单，再决定是否运行。',
      researchNote: '当前因预训练模型非商用条款进入 HOLD；禁止克隆未经同意的真实人物声音。',
    },
  },
  {
    title: 'Fish Speech Research',
    slug: 'awesome-fish-speech-research',
    summary: '跟踪高质量多语言语音生成，重点研究授权、溯源和滥用防护。',
    websiteUrl: 'https://speech.fish.audio/',
    sourceUrl: 'https://github.com/fishaudio/fish-speech',
    sortOrder: 210,
    dossier: {
      schema: AWESOME_PROJECT_SCHEMA,
      upstreamName: 'Fish Speech',
      direction: 'audio-production',
      license: 'FISH AUDIO RESEARCH LICENSE',
      licenseStatus: 'restricted',
      readiness: 'hold',
      compute: 'medium',
      artifact: 'VOICE SAFETY DOSSIER',
      effort: '1–2 DAYS',
      posture: 'STUDY',
      whyItMatters: '效果强但许可与身份滥用风险同样高，适合先建立本站的语音安全边界。',
      buildProposal: '把同意证明、生成声明、水印和用途限制设计成语音资产的必填字段。',
      firstMilestone: '完成最新版许可审计与安全门禁原型，不下载模型、不生成拟真人声。',
      researchNote: '当前只做观察和制度设计；重新启动前必须复查上游许可与安全政策。',
    },
  },
  // Game creation and asset pipelines
  {
    title: 'Godot Microgame Sprint',
    slug: 'awesome-godot-microgame-sprint',
    summary: '用开源引擎把视觉、音频与交互资产组合成一周内可玩的微型作品。',
    websiteUrl: 'https://godotengine.org/',
    sourceUrl: 'https://github.com/godotengine/godot',
    sortOrder: 220,
    dossier: {
      schema: AWESOME_PROJECT_SCHEMA,
      upstreamName: 'Godot Engine',
      direction: 'game-development',
      license: 'MIT',
      licenseStatus: 'clear',
      readiness: 'ready',
      compute: 'light',
      artifact: 'PLAYABLE MICROGAME',
      effort: '3–7 DAYS',
      posture: 'BUILD',
      whyItMatters: '游戏是检验图像、声音、叙事和交互是否真正能协同工作的最直接容器。',
      buildProposal: '每次只做一个核心机制，把用到的提示词、素材与代码模板回存为可复用配方。',
      firstMilestone: '用现有画廊风格做一个三分钟可通关的浏览器微游戏并记录资产来源。',
      researchNote: '引擎许可清晰；第三方插件、字体、音频和素材仍需逐项保留来源与条款。',
    },
  },
  {
    title: 'Bevy Systems Playground',
    slug: 'awesome-bevy-systems-playground',
    summary: '用 Rust ECS 探索高性能交互、生成式世界与数据驱动游戏架构。',
    websiteUrl: 'https://bevyengine.org/',
    sourceUrl: 'https://github.com/bevyengine/bevy',
    sortOrder: 230,
    dossier: {
      schema: AWESOME_PROJECT_SCHEMA,
      upstreamName: 'Bevy',
      direction: 'game-development',
      license: 'MIT OR APACHE-2.0',
      licenseStatus: 'clear',
      readiness: 'radar',
      compute: 'light',
      artifact: 'RUST GAME PROTOTYPE',
      effort: '4–8 DAYS',
      posture: 'STUDY',
      whyItMatters: '它适合把生成式内容与明确的数据系统结合，也能训练 Rust 与 ECS 的工程能力。',
      buildProposal: '从小型程序化场景入手，不追求完整游戏，重点沉淀可复用系统与调试工具。',
      firstMilestone: '生成一张小地图、十个实体和一个可观察的状态系统，导出 Web 试玩版本。',
      researchNote: '生态仍快速变化，启动时锁定版本并避免过早依赖大量第三方插件。',
    },
  },
  {
    title: 'Pixelorama Sprite Lab',
    slug: 'awesome-pixelorama-sprite-lab',
    summary: '把 AI 草图收敛为像素角色、动画帧和可直接进入游戏的图集。',
    websiteUrl: 'https://orama-interactive.itch.io/pixelorama',
    sourceUrl: 'https://github.com/Orama-Interactive/Pixelorama',
    sortOrder: 240,
    dossier: {
      schema: AWESOME_PROJECT_SCHEMA,
      upstreamName: 'Pixelorama',
      direction: 'game-development',
      license: 'MIT',
      licenseStatus: 'clear',
      readiness: 'ready',
      compute: 'light',
      artifact: 'ANIMATED SPRITESHEET',
      effort: '1–2 DAYS',
      posture: 'INTEGRATE',
      whyItMatters: '像素资产尺寸小、约束明确，很适合训练从生成灵感到人工可控交付的完整流程。',
      buildProposal: '建立角色规格、调色板、帧数和导出规则，并把提示词结果作为参考层而非成品。',
      firstMilestone: '完成一个八方向角色的待机与行走动画，导出 Godot 可直接使用的图集。',
      researchNote: '工具本身轻量；外部参考图和调色板仍需记录许可来源。',
    },
  },
  {
    title: 'Material Maker Texture Lab',
    slug: 'awesome-material-maker-texture-lab',
    summary: '用节点化流程生成无缝材质、纹理与游戏特效，形成可复跑配方。',
    websiteUrl: 'https://www.materialmaker.org/',
    sourceUrl: 'https://github.com/RodZill4/material-maker',
    sortOrder: 250,
    dossier: {
      schema: AWESOME_PROJECT_SCHEMA,
      upstreamName: 'Material Maker',
      direction: 'game-development',
      license: 'MIT',
      licenseStatus: 'clear',
      readiness: 'ready',
      compute: 'light',
      artifact: 'PBR MATERIAL PACK',
      effort: '1–3 DAYS',
      posture: 'BUILD',
      whyItMatters: '程序化材质比单张 AI 纹理更稳定，也能交付完整 PBR 通道和参数变体。',
      buildProposal: '为常用视觉风格建立材质配方，并同时输出预览图、节点图和引擎资产。',
      firstMilestone: '制作金属、石材和织物三套无缝材质，在 Godot 或 Blender 中完成实机预览。',
      researchNote: '适合低算力时段；导入的纹理与节点资源需要保留原始许可。',
    },
  },
  // Embedded systems and physical computing
  {
    title: 'LeRobot Desktop Arm Lab',
    slug: 'awesome-lerobot-desktop-arm-lab',
    summary: '从低成本机械臂、数据采集到模仿学习，建立一条可观察的机器人实验链。',
    websiteUrl: 'https://huggingface.co/lerobot',
    sourceUrl: 'https://github.com/huggingface/lerobot',
    sortOrder: 260,
    dossier: {
      schema: AWESOME_PROJECT_SCHEMA,
      upstreamName: 'LeRobot',
      direction: 'robotics',
      license: 'APACHE-2.0',
      licenseStatus: 'clear',
      readiness: 'radar',
      compute: 'heavy',
      artifact: 'ROBOT POLICY DEMO',
      effort: '5–10 DAYS',
      posture: 'STUDY',
      whyItMatters: '它把模型能力带到真实物理世界，也迫使数据、控制、安全和失败恢复同时落地。',
      buildProposal: '先用仿真或受限桌面任务验证数据链，再决定是否采购或组装硬件。',
      firstMilestone: '在无危险载荷的环境完成一次抓取任务，保存数据集版本、训练参数和失败视频。',
      researchNote: '涉及硬件与运动安全；启动前需要独立预算、急停方案和模型/数据许可核对。',
    },
  },
  {
    title: 'Genesis Embodied Sandbox',
    slug: 'awesome-genesis-embodied-sandbox',
    summary: '用高性能物理仿真探索机器人、软体与生成式场景，不先购买硬件。',
    websiteUrl: 'https://genesis-world.readthedocs.io/',
    sourceUrl: 'https://github.com/Genesis-Embodied-AI/Genesis',
    sortOrder: 270,
    dossier: {
      schema: AWESOME_PROJECT_SCHEMA,
      upstreamName: 'Genesis',
      direction: 'robotics',
      license: 'LICENSE REVIEW REQUIRED',
      licenseStatus: 'review',
      readiness: 'radar',
      compute: 'heavy',
      artifact: 'PHYSICS SIMULATION STUDY',
      effort: '3–6 DAYS',
      posture: 'STUDY',
      whyItMatters: '仿真能把高风险、高成本机器人想法先变成可重复数据与可视化实验。',
      buildProposal: '制作一个小型物体操作场景，比较渲染、物理速度和训练接口是否满足后续需求。',
      firstMilestone: '完成固定场景的千次仿真，输出稳定性、速度和失败分布报告。',
      researchNote: '项目与依赖更新较快；启动前锁定版本并重新核对软件、资产与模型许可。',
    },
  },
  {
    title: 'Isaac Lab Robot Bench',
    slug: 'awesome-isaac-lab-robot-bench',
    summary: '观察工业级 GPU 仿真与强化学习工具链，作为机器人方向能力上限。',
    websiteUrl: 'https://isaac-sim.github.io/IsaacLab/',
    sourceUrl: 'https://github.com/isaac-sim/IsaacLab',
    sortOrder: 280,
    dossier: {
      schema: AWESOME_PROJECT_SCHEMA,
      upstreamName: 'Isaac Lab',
      direction: 'robotics',
      license: 'BSD-3-CLAUSE / NVIDIA DEPENDENCIES',
      licenseStatus: 'review',
      readiness: 'radar',
      compute: 'heavy',
      artifact: 'GPU ROBOTICS BENCHMARK',
      effort: '3–7 DAYS',
      posture: 'STUDY',
      whyItMatters: '它代表一条成熟但重型的仿真路线，适合判断现有算力能否承担机器人训练。',
      buildProposal: '只做标准任务基准，不改本站架构；用结果决定是否进入长期机器人项目。',
      firstMilestone: '跑通一个官方示例，记录驱动、显存、帧率、训练速度和磁盘占用。',
      researchNote: '对 NVIDIA 软件栈和驱动版本敏感；安装前必须确认硬件兼容与依赖条款。',
    },
  },
  {
    title: 'LVGL Interface Bench',
    slug: 'awesome-lvgl-interface-bench',
    summary: '把网站设计能力迁移到 MCU 与小屏设备，建立可触摸的界面作品。',
    websiteUrl: 'https://lvgl.io/',
    sourceUrl: 'https://github.com/lvgl/lvgl',
    sortOrder: 290,
    dossier: {
      schema: AWESOME_PROJECT_SCHEMA,
      upstreamName: 'LVGL',
      direction: 'embedded-systems',
      license: 'MIT',
      licenseStatus: 'clear',
      readiness: 'ready',
      compute: 'light',
      artifact: 'EMBEDDED UI DEMO',
      effort: '2–4 DAYS',
      posture: 'BUILD',
      whyItMatters: '它能验证视觉系统在低分辨率、低内存与触摸输入下是否仍然清晰可用。',
      buildProposal: '把 KongXin 的一个主题缩减成嵌入式 token 与组件集，并在模拟器或开发板运行。',
      firstMilestone: '实现状态页、列表与仪表三屏，测量内存、帧率和不同尺寸的可读性。',
      researchNote: '软件可先在模拟器验证；连接真实硬件时再单独确认供电与刷写安全。',
    },
  },
  {
    title: 'Meshtastic Field Network',
    slug: 'awesome-meshtastic-field-network',
    summary: '用低功耗 LoRa 设备体验离线网状通信、地图与现场协作。',
    websiteUrl: 'https://meshtastic.org/',
    sourceUrl: 'https://github.com/meshtastic/firmware',
    sortOrder: 300,
    dossier: {
      schema: AWESOME_PROJECT_SCHEMA,
      upstreamName: 'Meshtastic',
      direction: 'embedded-systems',
      license: 'GPL-3.0',
      licenseStatus: 'clear',
      readiness: 'radar',
      compute: 'light',
      artifact: 'OFFLINE MESH DEMO',
      effort: '2–5 DAYS',
      posture: 'STUDY',
      whyItMatters: '它能探索断网环境下的真实通信产品，也连接地图、硬件和社区协作场景。',
      buildProposal: '先做两到三节点的非敏感消息实验，再考虑与本站项目日志建立只读桥接。',
      firstMilestone: '完成室内外覆盖测试，记录丢包、功耗、位置隐私和当地频段规则。',
      researchNote: '涉及无线电法规与位置隐私；购买和发射前确认所在地区允许频段及功率。',
    },
  },
  {
    title: 'ESPHome Ambient Console',
    slug: 'awesome-esphome-ambient-console',
    summary: '用声明式配置连接传感器、灯光和小屏，快速做一个环境控制台。',
    websiteUrl: 'https://esphome.io/',
    sourceUrl: 'https://github.com/esphome/esphome',
    sortOrder: 310,
    dossier: {
      schema: AWESOME_PROJECT_SCHEMA,
      upstreamName: 'ESPHome',
      direction: 'embedded-systems',
      license: 'GPL-3.0',
      licenseStatus: 'clear',
      readiness: 'ready',
      compute: 'light',
      artifact: 'SENSOR CONSOLE',
      effort: '1–3 DAYS',
      posture: 'INTEGRATE',
      whyItMatters: '低门槛硬件项目能把闲时算力之外的传感数据带回可视化与自动化创作。',
      buildProposal: '制作一块显示环境状态的桌面设备，只暴露本地网络，不接入不必要的云服务。',
      firstMilestone: '接入温湿度与光照传感器，在小屏显示并保存一天的本地趋势。',
      researchNote: '刷写前核对具体板卡与引脚，家电控制等高压场景不纳入首期实验。',
    },
  },
  {
    title: 'WLED Generative Light',
    slug: 'awesome-wled-generative-light',
    summary: '把配色、动效与音乐反应变成可触摸的灯光作品和空间氛围样本。',
    websiteUrl: 'https://kno.wled.ge/',
    sourceUrl: 'https://github.com/wled/WLED',
    sortOrder: 320,
    dossier: {
      schema: AWESOME_PROJECT_SCHEMA,
      upstreamName: 'WLED',
      direction: 'embedded-systems',
      license: 'EUPL-1.2',
      licenseStatus: 'clear',
      readiness: 'ready',
      compute: 'light',
      artifact: 'GENERATIVE LIGHT SCENE',
      effort: '1–2 DAYS',
      posture: 'BUILD',
      whyItMatters: '它把屏幕里的视觉风格延伸到物理空间，且成本低、反馈快、容易形成展示作品。',
      buildProposal: '设计几组与本站主题相呼应的色彩和节奏，并记录灯带、电源与预设配置。',
      firstMilestone: '完成一个安全供电的小型灯带装置，制作三套可一键切换的空间预设。',
      researchNote: '首期限制为低压小功率；电源容量、散热和接线必须按硬件规格检查。',
    },
  },
  {
    title: 'Zephyr Device Systems Lab',
    slug: 'awesome-zephyr-device-systems-lab',
    summary: '用工业级 RTOS 练习设备驱动、并发、功耗与长期可维护固件。',
    websiteUrl: 'https://www.zephyrproject.org/',
    sourceUrl: 'https://github.com/zephyrproject-rtos/zephyr',
    sortOrder: 330,
    dossier: {
      schema: AWESOME_PROJECT_SCHEMA,
      upstreamName: 'Zephyr',
      direction: 'embedded-systems',
      license: 'APACHE-2.0',
      licenseStatus: 'clear',
      readiness: 'radar',
      compute: 'light',
      artifact: 'RTOS DEVICE PROTOTYPE',
      effort: '4–8 DAYS',
      posture: 'STUDY',
      whyItMatters: '它适合从玩具级原型过渡到结构清晰、可测试、可持续维护的设备软件。',
      buildProposal: '选一块已支持的开发板，做传感、休眠与通信的最小系统并建立硬件在环测试。',
      firstMilestone: '跑通三个线程、低功耗唤醒和一次 OTA 或串口升级，记录功耗与失败恢复。',
      researchNote: '生态庞大且配置复杂；首期只使用官方支持板卡与样例，避免无边界移植。',
    },
  },
  // Agents, local models and serving infrastructure
  {
    title: 'OpenHands Coding Arena',
    slug: 'awesome-openhands-coding-arena',
    summary: '在隔离仓库里评估自主编码代理处理真实 Issue 的能力、成本与风险。',
    websiteUrl: 'https://www.all-hands.dev/',
    sourceUrl: 'https://github.com/OpenHands/OpenHands',
    sortOrder: 340,
    dossier: {
      schema: AWESOME_PROJECT_SCHEMA,
      upstreamName: 'OpenHands',
      direction: 'developer-tools',
      license: 'MIT CORE / ENTERPRISE EXCEPTIONS',
      licenseStatus: 'review',
      readiness: 'radar',
      compute: 'medium',
      artifact: 'AGENT TASK BENCHMARK',
      effort: '2–4 DAYS',
      posture: 'STUDY',
      whyItMatters: '它能把“代理会写代码”变成在受控任务、补丁质量、成本和失败模式上的真实数据。',
      buildProposal: '只在一次性容器和无秘密测试仓库运行，输出补丁、轨迹和人工复核结果。',
      firstMilestone: '选择五个已知答案的小 Issue，对比完成率、越权行为、测试通过率和 token 成本。',
      researchNote: '自主代理可执行命令与网络请求；必须隔离凭据、目录、网络和资源预算。',
    },
  },
  {
    title: 'Aider Pairing Bench',
    slug: 'awesome-aider-pairing-bench',
    summary: '评估终端式 AI 结对编程在小范围改动、测试和 Git 轨迹上的可控性。',
    websiteUrl: 'https://aider.chat/',
    sourceUrl: 'https://github.com/Aider-AI/aider',
    sortOrder: 350,
    dossier: {
      schema: AWESOME_PROJECT_SCHEMA,
      upstreamName: 'Aider',
      direction: 'developer-tools',
      license: 'APACHE-2.0',
      licenseStatus: 'clear',
      readiness: 'ready',
      compute: 'light',
      artifact: 'PAIR PROGRAMMING REPORT',
      effort: '1–2 DAYS',
      posture: 'STUDY',
      whyItMatters: '它提供一个较轻量的代理对照，可以帮助判断不同编码工作流何时真正节省人工。',
      buildProposal: '用相同任务与 Codex/现有流程做盲评，只比较结果，不把工具直接接入生产仓库。',
      firstMilestone: '完成三个小修复，记录上下文量、补丁尺寸、测试结果与人工返工时间。',
      researchNote: '实验仓库不含生产密钥；所有提交仍需人工审阅，工具不获得 push 权限。',
    },
  },
  {
    title: 'llama.cpp Local Model Deck',
    slug: 'awesome-llama-cpp-local-model-deck',
    summary: '在 CPU 与本地 GPU 上整理可运行模型、量化级别和真实吞吐能力。',
    websiteUrl: 'https://github.com/ggml-org/llama.cpp',
    sourceUrl: 'https://github.com/ggml-org/llama.cpp',
    sortOrder: 360,
    dossier: {
      schema: AWESOME_PROJECT_SCHEMA,
      upstreamName: 'llama.cpp',
      direction: 'model-infra',
      license: 'MIT',
      licenseStatus: 'clear',
      readiness: 'ready',
      compute: 'medium',
      artifact: 'LOCAL MODEL BENCHMARK',
      effort: '1–3 DAYS',
      posture: 'INTEGRATE',
      whyItMatters: '它能把闲置 CPU/GPU 变成私有推理节点，并用真实数据判断哪些模型值得长期保留。',
      buildProposal: '建立设备、模型、量化、上下文、吞吐与质量的能力卡，供 Prompt 工作台路由。',
      firstMilestone: '选三个尺寸模型，运行固定文本集并记录速度、内存、质量和模型许可。',
      researchNote: '代码许可清晰，但每个模型权重拥有独立条款；下载前逐个记录来源与许可。',
    },
  },
  {
    title: 'vLLM Throughput Lab',
    slug: 'awesome-vllm-throughput-lab',
    summary: '测试多请求、高吞吐和 OpenAI 兼容推理服务是否适合现有 GPU。',
    websiteUrl: 'https://docs.vllm.ai/',
    sourceUrl: 'https://github.com/vllm-project/vllm',
    sortOrder: 370,
    dossier: {
      schema: AWESOME_PROJECT_SCHEMA,
      upstreamName: 'vLLM',
      direction: 'model-infra',
      license: 'APACHE-2.0',
      licenseStatus: 'clear',
      readiness: 'ready',
      compute: 'heavy',
      artifact: 'INFERENCE CAPACITY REPORT',
      effort: '1–3 DAYS',
      posture: 'STUDY',
      whyItMatters: '单次能跑不代表可服务；并发、显存碎片、首 token 和持续吞吐决定真实可用性。',
      buildProposal: '用隔离端口跑兼容 API 基准，再决定是否作为 CPA 后端候选。',
      firstMilestone: '固定一个允许使用的模型，测试四档并发下的延迟、吞吐、显存和错误率。',
      researchNote: '需要兼容 GPU 与 CUDA 版本；不开放公网，不加载许可未知的模型。',
    },
  },
  {
    title: 'SGLang Serving Trial',
    slug: 'awesome-sglang-serving-trial',
    summary: '探索结构化生成、前缀缓存和多模态服务在复杂工作流中的收益。',
    websiteUrl: 'https://docs.sglang.ai/',
    sourceUrl: 'https://github.com/sgl-project/sglang',
    sortOrder: 380,
    dossier: {
      schema: AWESOME_PROJECT_SCHEMA,
      upstreamName: 'SGLang',
      direction: 'model-infra',
      license: 'APACHE-2.0',
      licenseStatus: 'clear',
      readiness: 'radar',
      compute: 'heavy',
      artifact: 'SERVING COMPARISON',
      effort: '2–4 DAYS',
      posture: 'STUDY',
      whyItMatters: '它可以与 vLLM 形成有意义的服务层对照，避免仅凭社区热度选择基础设施。',
      buildProposal: '使用相同模型、请求集和硬件比较缓存、结构化输出、吞吐和运维复杂度。',
      firstMilestone: '跑完一组与 vLLM 同条件基准，输出是否继续跟进的明确结论。',
      researchNote: '只在隔离环境试验，锁定版本并记录编译依赖与模型条款。',
    },
  },
  {
    title: 'BentoML Model Service Kit',
    slug: 'awesome-bentoml-model-service-kit',
    summary: '把一个已验证模型包装成有健康检查、版本与资源边界的可部署服务。',
    websiteUrl: 'https://www.bentoml.com/',
    sourceUrl: 'https://github.com/bentoml/BentoML',
    sortOrder: 390,
    dossier: {
      schema: AWESOME_PROJECT_SCHEMA,
      upstreamName: 'BentoML',
      direction: 'model-infra',
      license: 'APACHE-2.0',
      licenseStatus: 'clear',
      readiness: 'radar',
      compute: 'medium',
      artifact: 'VERSIONED MODEL SERVICE',
      effort: '2–4 DAYS',
      posture: 'STUDY',
      whyItMatters: '模型实验要进入产品，需要稳定接口、依赖封装、观测与资源限制，而不是永久运行临时脚本。',
      buildProposal: '选择一项已经通过评测的本地能力，打包为只在局域网开放的版本化服务。',
      firstMilestone: '完成一个带健康检查、超时、并发限制和可回滚版本的最小服务。',
      researchNote: '只包装已核验模型；镜像、权重和运行日志分别管理，避免把秘密写入构建产物。',
    },
  },
  // Knowledge, documents and creative communication
  {
    title: 'Docling Document Ingest',
    slug: 'awesome-docling-document-ingest',
    summary: '把 PDF、Office 与复杂版式转成结构化内容，保留页面与来源坐标。',
    websiteUrl: 'https://docling-project.github.io/docling/',
    sourceUrl: 'https://github.com/docling-project/docling',
    sortOrder: 400,
    dossier: {
      schema: AWESOME_PROJECT_SCHEMA,
      upstreamName: 'Docling',
      direction: 'knowledge-tools',
      license: 'MIT',
      licenseStatus: 'clear',
      readiness: 'ready',
      compute: 'medium',
      artifact: 'TRACEABLE DOCUMENT CORPUS',
      effort: '1–3 DAYS',
      posture: 'INTEGRATE',
      whyItMatters: '文章与 Prompt 的外部资料只有保留文档、页面和结构坐标，后续引用才真正可审计。',
      buildProposal: '把解析结果先作为 Candidate 来源保存，不直接发布，并保留原文件哈希与访问权限。',
      firstMilestone: '解析三份复杂 PDF，验证表格、图片、标题和页码能否稳定回指原文。',
      researchNote: '只处理用户有权使用的文档；原件、解析结果与公开内容的权限必须分离。',
    },
  },
  {
    title: 'MinerU Layout Comparison',
    slug: 'awesome-mineru-layout-comparison',
    summary: '对照测试复杂 PDF、公式和多栏版式解析，先审计额外许可条款。',
    websiteUrl: 'https://opendatalab.github.io/MinerU/',
    sourceUrl: 'https://github.com/opendatalab/MinerU',
    sortOrder: 410,
    dossier: {
      schema: AWESOME_PROJECT_SCHEMA,
      upstreamName: 'MinerU',
      direction: 'knowledge-tools',
      license: 'AGPL-3.0 / ADDITIONAL TERMS REVIEW',
      licenseStatus: 'review',
      readiness: 'hold',
      compute: 'medium',
      artifact: 'DOCUMENT PARSER COMPARISON',
      effort: '1–2 DAYS',
      posture: 'STUDY',
      whyItMatters: '解析质量值得与 Docling 对照，但附加条款需要先于任何集成决定。',
      buildProposal: '只在许可结论清晰后，用同一公开文档集做离线质量比较。',
      firstMilestone: '完成代码、模型与服务条款审计，并准备不含私人数据的基准集。',
      researchNote: '当前因许可核对进入 HOLD；不安装、不下载模型，也不上传用户文档。',
    },
  },
  {
    title: 'Excalidraw Visual Notes',
    slug: 'awesome-excalidraw-visual-notes',
    summary: '把研究、系统关系和客户思路变成轻量、可编辑、可分享的手绘图。',
    websiteUrl: 'https://excalidraw.com/',
    sourceUrl: 'https://github.com/excalidraw/excalidraw',
    sortOrder: 420,
    dossier: {
      schema: AWESOME_PROJECT_SCHEMA,
      upstreamName: 'Excalidraw',
      direction: 'knowledge-tools',
      license: 'MIT',
      licenseStatus: 'clear',
      readiness: 'ready',
      compute: 'light',
      artifact: 'EDITABLE VISUAL NOTE',
      effort: '1–2 DAYS',
      posture: 'INTEGRATE',
      whyItMatters: '一些想法用图比文章更清楚，也能让社区沉淀和项目档案拥有可编辑视觉证据。',
      buildProposal: '研究只读嵌入与文件归档，不直接搬入完整编辑器，先建立图与来源对象的连接。',
      firstMilestone: '为一个真实项目制作架构、用户流和决策三张图，并验证导出与回编。',
      researchNote: '嵌入前检查资源体积与数据边界；协作服务不是首期目标。',
    },
  },
  {
    title: 'Typst Report Foundry',
    slug: 'awesome-typst-report-foundry',
    summary: '把评测矩阵、项目档案与客户方案生成高质量、可版本化的 PDF。',
    websiteUrl: 'https://typst.app/',
    sourceUrl: 'https://github.com/typst/typst',
    sortOrder: 430,
    dossier: {
      schema: AWESOME_PROJECT_SCHEMA,
      upstreamName: 'Typst',
      direction: 'presentation',
      license: 'APACHE-2.0',
      licenseStatus: 'clear',
      readiness: 'ready',
      compute: 'light',
      artifact: 'VERSIONED PDF REPORT',
      effort: '1–3 DAYS',
      posture: 'BUILD',
      whyItMatters: '它能把结构化数据与精致排版放进 Git 版本链，补齐非幻灯片类文档交付。',
      buildProposal: '制作两套本站报告模板：Prompt 实验报告与视觉风格提案，并只接受受限数据结构。',
      firstMilestone: '从现有 Awesome 数据生成一份含目录、表格、链接和许可标记的 PDF。',
      researchNote: '模板与字体许可分别记录；生成器不执行用户提供的任意脚本。',
    },
  },
  {
    title: 'Manim Concept Cinema',
    slug: 'awesome-manim-concept-cinema',
    summary: '用代码把抽象概念、算法和数据关系制作成可复现的解释动画。',
    websiteUrl: 'https://www.manim.community/',
    sourceUrl: 'https://github.com/ManimCommunity/manim',
    sortOrder: 440,
    dossier: {
      schema: AWESOME_PROJECT_SCHEMA,
      upstreamName: 'Manim Community',
      direction: 'video-production',
      license: 'MIT',
      licenseStatus: 'clear',
      readiness: 'ready',
      compute: 'medium',
      artifact: 'EXPLANATION ANIMATION',
      effort: '2–5 DAYS',
      posture: 'BUILD',
      whyItMatters: '它提供与生成式视频不同的确定性路线，适合技术、教育与产品概念表达。',
      buildProposal: '把一段文章或架构数据转成受控场景脚本，人工调整节奏与构图后渲染。',
      firstMilestone: '选择一个本站真实工作流，制作三十秒动画并保存源码、配音与渲染参数。',
      researchNote: '动画脚本属于可执行代码，只运行本站生成且人工检查过的场景文件。',
    },
  },
  // Useful self-hosted systems
  {
    title: 'Immich Visual Archive',
    slug: 'awesome-immich-visual-archive',
    summary: '在本地管理照片与视频，为灵感、客户素材和生成结果建立可靠时间线。',
    websiteUrl: 'https://immich.app/',
    sourceUrl: 'https://github.com/immich-app/immich',
    sortOrder: 450,
    dossier: {
      schema: AWESOME_PROJECT_SCHEMA,
      upstreamName: 'Immich',
      direction: 'self-hosted',
      license: 'AGPL-3.0',
      licenseStatus: 'clear',
      readiness: 'radar',
      compute: 'medium',
      artifact: 'PRIVATE MEDIA ARCHIVE',
      effort: '2–4 DAYS',
      posture: 'STUDY',
      whyItMatters: '视觉创作需要长期可检索的原图、结果与时间线，但这类数据也最不能丢失。',
      buildProposal: '先在副本和独立存储上验证导入、搜索、备份与恢复，不替换现有原始素材目录。',
      firstMilestone: '导入一份可删除的测试副本，完成元数据校验、备份和从零恢复演练。',
      researchNote: '项目明确不应作为唯一备份；原始数据保持独立，升级前必须先完成可验证备份。',
    },
  },
  {
    title: 'Paperless Knowledge Inbox',
    slug: 'awesome-paperless-knowledge-inbox',
    summary: '把票据、说明书与扫描文档变成可搜索、可标注、可归档的私人资料库。',
    websiteUrl: 'https://docs.paperless-ngx.com/',
    sourceUrl: 'https://github.com/paperless-ngx/paperless-ngx',
    sortOrder: 460,
    dossier: {
      schema: AWESOME_PROJECT_SCHEMA,
      upstreamName: 'Paperless-ngx',
      direction: 'self-hosted',
      license: 'GPL-3.0',
      licenseStatus: 'clear',
      readiness: 'ready',
      compute: 'light',
      artifact: 'SEARCHABLE DOCUMENT INBOX',
      effort: '1–3 DAYS',
      posture: 'STUDY',
      whyItMatters: '它能承接日常文档沉淀，并为 Docling 等结构化实验提供清晰的私有数据边界。',
      buildProposal: '只用脱敏测试文档验证 OCR、标签、导出与恢复，再决定是否接入真实资料。',
      firstMilestone: '导入二十份测试文档，完成标签规则、全文搜索和完整导出恢复。',
      researchNote: '私人文档默认不出局域网；数据库、媒体目录和密钥必须纳入独立备份。',
    },
  },
  {
    title: 'SearXNG Research Portal',
    slug: 'awesome-searxng-research-portal',
    summary: '搭建私有元搜索入口，为选题与开源调研减少平台画像和结果锁定。',
    websiteUrl: 'https://docs.searxng.org/',
    sourceUrl: 'https://github.com/searxng/searxng',
    sortOrder: 470,
    dossier: {
      schema: AWESOME_PROJECT_SCHEMA,
      upstreamName: 'SearXNG',
      direction: 'self-hosted',
      license: 'AGPL-3.0',
      licenseStatus: 'clear',
      readiness: 'radar',
      compute: 'light',
      artifact: 'PRIVATE SEARCH PORTAL',
      effort: '1–2 DAYS',
      posture: 'STUDY',
      whyItMatters: '长期项目发现需要多来源搜索和可控隐私，而不是被单一商业搜索排序限制。',
      buildProposal: '先作为局域网研究工具使用，不与本站用户数据或自动抓取流水线连接。',
      firstMilestone: '配置五类搜索源，测试中文、代码与学术查询的覆盖、延迟和失败降级。',
      researchNote: '遵守各搜索源使用条款并限制请求频率；实例不公开为公共代理。',
    },
  },
  {
    title: 'Home Assistant Creative Space',
    slug: 'awesome-home-assistant-creative-space',
    summary: '把灯光、传感器和设备状态组合成一个可编排的创作空间控制面板。',
    websiteUrl: 'https://www.home-assistant.io/',
    sourceUrl: 'https://github.com/home-assistant/core',
    sortOrder: 480,
    dossier: {
      schema: AWESOME_PROJECT_SCHEMA,
      upstreamName: 'Home Assistant Core',
      direction: 'self-hosted',
      license: 'APACHE-2.0',
      licenseStatus: 'clear',
      readiness: 'ready',
      compute: 'light',
      artifact: 'CREATIVE SPACE DASHBOARD',
      effort: '2–5 DAYS',
      posture: 'INTEGRATE',
      whyItMatters: '它能把 WLED、ESPHome 与房间状态合并成实际可用的空间体验，而非孤立硬件演示。',
      buildProposal: '建立完全本地的创作模式，只接入必要设备并限制自动化的物理影响范围。',
      firstMilestone: '完成工作、展示和休息三种场景，手动触发并保留所有设备的安全回退。',
      researchNote: '首期不控制门锁、加热器等高风险设备；配置、密钥和历史数据分开备份。',
    },
  },
  // Scientific imaging and analysis
  {
    title: 'Cellpose Microscopy Trial',
    slug: 'awesome-cellpose-microscopy-trial',
    summary: '体验通用细胞分割，把闲置 GPU 用于有客观指标的科学图像实验。',
    websiteUrl: 'https://www.cellpose.org/',
    sourceUrl: 'https://github.com/MouseLand/cellpose',
    sortOrder: 490,
    dossier: {
      schema: AWESOME_PROJECT_SCHEMA,
      upstreamName: 'Cellpose',
      direction: 'science',
      license: 'BSD-3-CLAUSE CODE / MODEL TERMS REVIEW',
      licenseStatus: 'review',
      readiness: 'radar',
      compute: 'medium',
      artifact: 'SEGMENTATION BENCHMARK',
      effort: '2–4 DAYS',
      posture: 'STUDY',
      whyItMatters: '与纯审美生成不同，科学分割能用标注和指标验证模型效果，拓展算力的实际用途。',
      buildProposal: '只使用公开非敏感数据集，比较预训练模型与人工修正成本，不做医疗结论。',
      firstMilestone: '在一个公开小数据集上运行分割，报告准确性、速度、失败类型和许可。',
      researchNote: '模型与数据集可能有额外非商用条件；本站结果只用于研究，不用于诊断。',
    },
  },
  {
    title: 'napari Visual Science Desk',
    slug: 'awesome-napari-visual-science-desk',
    summary: '用多维图像查看器检查显微、分割与体数据，建立科学可视化入口。',
    websiteUrl: 'https://napari.org/',
    sourceUrl: 'https://github.com/napari/napari',
    sortOrder: 500,
    dossier: {
      schema: AWESOME_PROJECT_SCHEMA,
      upstreamName: 'napari',
      direction: 'science',
      license: 'BSD-3-CLAUSE',
      licenseStatus: 'clear',
      readiness: 'ready',
      compute: 'medium',
      artifact: 'INTERACTIVE SCIENCE VIEW',
      effort: '1–2 DAYS',
      posture: 'INTEGRATE',
      whyItMatters: '高维结果需要可交互检查，而不是只保存一张最终截图；它也适合作为 Cellpose 输出审阅台。',
      buildProposal: '建立一个只读插件或导出流程，把公开数据、模型结果和人工修正并排显示。',
      firstMilestone: '加载一组公开三维图像与分割标签，完成切片、图层、测量和导出实验。',
      researchNote: '只使用许可明确的数据与插件；大型数据先做副本和内存预算。',
    },
  },
]

export const AWESOME_PROJECTS: AwesomeProjectSeed[] = AWESOME_PROJECT_INPUTS.map(
  defineAwesomeProject,
)

export function awesomeCandidateTags(project: AwesomeProjectSeed): string[] {
  return [
    'awesome',
    'catalog:project',
    `direction:${project.dossier.direction}`,
    `readiness:${project.dossier.readiness}`,
    `compute:${project.dossier.compute}`,
    `license-status:${project.dossier.licenseStatus}`,
    `upstream:${project.dossier.upstreamName.toLowerCase()}`,
  ]
}

export function awesomeDossierJson(project: AwesomeProjectSeed): string {
  return JSON.stringify(project.dossier)
}

export function backfillAwesomeDossierJson(
  rawContent: string | null,
  project: AwesomeProjectSeed,
): string | null {
  if (!rawContent) return null

  try {
    const parsed = JSON.parse(rawContent) as Record<string, unknown>
    if (parsed.schema !== AWESOME_PROJECT_SCHEMA) return null

    const next = { ...parsed }
    let changed = false
    for (const key of ['readiness', 'compute', 'artifact', 'licenseStatus'] as const) {
      if (!(key in next)) {
        next[key] = project.dossier[key]
        changed = true
      }
    }
    return changed ? JSON.stringify(next) : rawContent
  } catch {
    return null
  }
}

export function backfillAwesomeTags(
  rawTags: string,
  project: AwesomeProjectSeed,
): string | null {
  try {
    const parsed = JSON.parse(rawTags) as unknown
    if (!Array.isArray(parsed) || !parsed.every((tag) => typeof tag === 'string')) return null

    const next = [...parsed]
    for (const tag of awesomeCandidateTags(project)) {
      if (!next.includes(tag)) next.push(tag)
    }
    return next.length === parsed.length ? rawTags : JSON.stringify(next)
  } catch {
    return null
  }
}
